// Spanish, German and French UI texts (keys are the English texts, same as the Turkish table in i18n.js). Missing keys fall back to English.
DICT.es = {
  'Close menu': 'Cerrar menú', 'Open menu': 'Abrir menú', 'Mode': 'Modo', 'Normal': 'Normal', 'Plane spotter': 'Spotter de aviones', 'Data': 'Datos', 'Demo': 'Demo', 'Live': 'En vivo',
  'Map': 'Mapa', 'Airports': 'Aeropuertos', 'Alert zone': 'Zona de alerta', 'Radar': 'Radar', 'Rain radar': 'Radar de lluvia', 'Zone radius': 'Radio de la zona',
  'High turbulence risk ahead (~{0} km)': 'Riesgo alto de turbulencia por delante (~{0} km)', 'Moderate turbulence possible ahead (~{0} km)': 'Posible turbulencia moderada por delante (~{0} km)',
  'No turbulence reported or forecast on the route ahead': 'Sin turbulencias notificadas ni previstas en la ruta', 'Turbulence info unavailable': 'Información de turbulencia no disponible', 'Checking route ahead…': 'Comprobando la ruta…',
  'Wind': 'Viento', 'Headwind {0} kt': 'Viento de cara {0} kt', 'Tailwind {0} kt': 'Viento de cola {0} kt', 'No significant head/tailwind': 'Sin viento de cara/cola relevante', '~{0}% of tank left (est., incl. reserve)': '~{0}% del depósito restante (est., con reserva)', 'Fuel to go (est.)': 'Combustible restante (est.)', 'arrives {0}': 'llega {0}',
  'Turbulence': 'Turbulencia', 'Turbulence advisories (SIGMET / G-AIRMET)': 'Avisos de turbulencia (SIGMET / G-AIRMET)', 'Wind arrows': 'Flechas de viento', 'Wind: FL050': 'Viento: FL050', 'Wind: FL100': 'Viento: FL100', 'Wind: FL180': 'Viento: FL180', 'Wind: FL300': 'Viento: FL300', 'Wind: FL340': 'Viento: FL340', 'Wind: FL390': 'Viento: FL390', 'Night': 'Noche', 'Day / night': 'Día / noche',
  'Wind at {0}': 'Viento a {0}', 'Wind data unavailable': 'Datos de viento no disponibles', 'Turbulence data unavailable': 'Datos de turbulencia no disponibles', 'Moderate turbulence': 'Turbulencia moderada', 'Severe turbulence': 'Turbulencia severa', 'No turbulence advisories right now': 'Sin avisos de turbulencia ahora',
  'Aircraft': 'Aeronaves', '{0} s ago': 'hace {0} s', '{0} min ago': 'hace {0} min',
  'Standard': 'Estándar', 'Light': 'Claro', 'Dark': 'Oscuro', 'Filters': 'Filtros', 'Altitude': 'Altitud', 'Min speed': 'Velocidad mín.', 'Airport': 'Aeropuerto',
  'Departure': 'Salida', 'Arrival': 'Llegada', 'Departure ↔ arrival': 'Salida ↔ llegada', 'Airline': 'Aerolínea', 'e.g. THY, Pegasus, Lufthansa': 'p. ej. Iberia, Vueling, Lufthansa',
  'Aircraft type': 'Tipo de aeronave', 'e.g. B738, A320, boeing 777': 'p. ej. B738, A320, boeing 777', 'Show aircraft on the ground': 'Mostrar aeronaves en tierra',
  'Favorites only ★': 'Solo favoritos ★', 'Search callsign or registration…': 'Buscar indicativo o matrícula…',
  '● Live': '● En vivo', 'history': 'historial', 'min': 'mín', 'max': 'máx', ' min': ' min', ' h ': ' h ',
  'on ground': 'en tierra', 'landed': 'aterrizó', 'Close': 'Cerrar', 'Open photo': 'Abrir foto', 'Previous photo': 'Foto anterior', 'Next photo': 'Foto siguiente', 'Photo': 'Foto',
  '{0} entered the alert zone': '{0} entró en la zona de alerta', 'loading…': 'cargando…', 'error': 'error', 'last updated': 'última actualización',
  'wide view: center only, zoom in': 'vista amplia: solo el centro, acerca el mapa', 'demo (30x speed)': 'demo (velocidad ×30)', 'FLIGHTS': 'VUELOS',
  'loading route info · {0} / {1} aircraft': 'cargando rutas · {0} / {1} aeronaves', 'Click the map to set the zone center': 'Haz clic en el mapa para fijar el centro de la zona',
  'Alert zone set ({0} km)': 'Zona de alerta fijada ({0} km)', '{0} km flown · {1} km to go': '{0} km recorridos · {1} km restantes',
  'Registration': 'Matrícula', 'Speed': 'Velocidad', 'Heading': 'Rumbo', 'Vertical speed': 'Velocidad vertical', 'Nearest airport': 'Aeropuerto más cercano', 'Position': 'Posición', 'Owner': 'Propietario',
  '★ Favorited': '★ En favoritos', '☆ Favorite': '☆ Favorito', 'Loading route info…': 'Cargando ruta…', 'Route info not found': 'Ruta no encontrada',
  "Couldn't load route info": 'No se pudo cargar la ruta', 'ICAO24': 'ICAO24', 'Squawk': 'Squawk', 'Category': 'Categoría', 'Country': 'País',
  "Couldn't load airport info": 'No se pudo cargar la información del aeropuerto', 'Loading…': 'Cargando…', 'Open on Wikipedia': 'Abrir en Wikipedia', 'Feels like': 'Sensación', 'Gusts': 'Rachas',
  'Humidity': 'Humedad', 'Pressure': 'Presión', 'Visibility': 'Visibilidad', 'Arrivals': 'Llegadas', 'Departures': 'Salidas', 'Weather unavailable': 'Tiempo no disponible',
  'Loading weather…': 'Cargando el tiempo…', 'No aircraft loaded yet': 'Aún no hay aeronaves cargadas', 'No arrivals found nearby': 'No hay llegadas cerca', 'No departures found nearby': 'No hay salidas cerca',
  'Clear sky': 'Despejado', 'Mostly clear': 'Mayormente despejado', 'Partly cloudy': 'Parcialmente nublado', 'Overcast': 'Cubierto', 'Fog': 'Niebla', 'Freezing fog': 'Niebla helada', 'Light drizzle': 'Llovizna ligera',
  'Drizzle': 'Llovizna', 'Heavy drizzle': 'Llovizna intensa', 'Freezing drizzle': 'Llovizna helada', 'Light rain': 'Lluvia ligera', 'Rain': 'Lluvia', 'Heavy rain': 'Lluvia fuerte',
  'Freezing rain': 'Lluvia helada', 'Light snow': 'Nieve ligera', 'Snow': 'Nieve', 'Heavy snow': 'Nieve intensa', 'Snow grains': 'Granos de nieve', 'Rain showers': 'Chubascos', 'Violent showers': 'Chubascos fuertes',
  'Snow showers': 'Chubascos de nieve', 'Thunderstorm': 'Tormenta', 'Thunderstorm, hail': 'Tormenta con granizo',
  'Hijacking': 'Secuestro', 'Radio failure': 'Fallo de radio', 'General emergency': 'Emergencia general', 'Emergency': 'Emergencia', 'What does this code mean?': '¿Qué significa este código?',
  '{0} landed': '{0} ha aterrizado', '{0} took off': '{0} ha despegado', 'Watching {0}: you will be notified when it takes off or lands': 'Siguiendo {0}: recibirás un aviso al despegar o aterrizar',
  'Watchlist': 'Lista de seguimiento', 'last seen {0} min ago': 'visto hace {0} min', 'not seen yet': 'aún no visto', 'Remove': 'Quitar', 'Not on the map right now': 'No está en el mapa ahora',
  '🔔 Watching': '🔔 Siguiendo', '🔔 Watch': '🔔 Seguir', "Today's flights": 'Vuelos de hoy', "Couldn't load today's flights": 'No se pudieron cargar los vuelos de hoy',
  'No flights recorded today': 'Hoy no hay vuelos registrados', 'in flight': 'en vuelo', 'now': 'ahora', 'Radar unavailable': 'Radar no disponible',
  'Already logged': 'Ya registrado', 'new aircraft': 'aeronave nueva', 'new type': 'tipo nuevo', 'Logged {0}': '{0} registrado', 'Logbook': 'Cuaderno', 'aircraft': 'aeronaves', 'types': 'tipos',
  'airlines': 'aerolíneas', 'Open logbook': 'Abrir cuaderno', 'Export CSV': 'Exportar CSV', 'The logbook is empty': 'El cuaderno está vacío', 'Search the logbook…': 'Buscar en el cuaderno…',
  'Nothing matches': 'Sin coincidencias', 'The logbook is empty. Open a flight and press “Log sighting”.': 'El cuaderno está vacío. Abre un vuelo y pulsa «Registrar avistamiento».',
  'NEW AIRCRAFT': 'AERONAVE NUEVA', 'NEW TYPE': 'TIPO NUEVO', '✓ Logged': '✓ Registrado', '📓 Log sighting': '📓 Registrar avistamiento',
  'Vert. speed': 'Vel. vertical', 'SkyTrack keeps running in the tray when you close the window': 'SkyTrack sigue funcionando en la bandeja al cerrar la ventana', '📓 Flight diary': '📓 Diario de vuelos',
  'Keep running in the tray': 'Seguir en la bandeja del sistema', 'Desktop notifications': 'Notificaciones de escritorio', 'Flight diary': 'Diario de vuelos', 'Flights': 'Vuelos', 'Distance': 'Distancia', 'Around the Earth': 'Vueltas al mundo',
  '(est.)': '(est.)', 'From': 'Origen', 'To': 'Destino', 'Flight no.': 'N.º de vuelo', 'Add': 'Añadir',
  'Your diary is empty. Add a flight above, or open a flight on the map and press “Add to diary”.': 'Tu diario está vacío. Añade un vuelo arriba o abre uno en el mapa y pulsa «Añadir al diario».',
  'Unknown airport: use an IATA or ICAO code, e.g. IST or LTFM': 'Aeropuerto desconocido: usa un código IATA u OACI, p. ej. MAD o LEMD', 'Share image': 'Compartir imagen', 'Add to diary': 'Añadir al diario', 'Added to your diary': 'Añadido a tu diario',
  'Free flight tracker · no account, no ads': 'Seguimiento de vuelos gratis · sin cuenta ni anuncios', 'Image saved and copied to the clipboard': 'Imagen guardada y copiada al portapapeles', 'Image saved': 'Imagen guardada', 'Altitude & speed': 'Altitud y velocidad',
  'Landing': 'Aterrizando', 'Approaching': 'Aproximándose', 'Departed': 'Ha salido', 'En route': 'En ruta'
};
DICT.de = {
  'Close menu': 'Menü schließen', 'Open menu': 'Menü öffnen', 'Mode': 'Modus', 'Normal': 'Normal', 'Plane spotter': 'Planespotter', 'Data': 'Daten', 'Demo': 'Demo', 'Live': 'Live',
  'Map': 'Karte', 'Airports': 'Flughäfen', 'Alert zone': 'Alarmzone', 'Radar': 'Radar', 'Rain radar': 'Regenradar', 'Zone radius': 'Zonenradius',
  'High turbulence risk ahead (~{0} km)': 'Hohes Turbulenzrisiko voraus (~{0} km)', 'Moderate turbulence possible ahead (~{0} km)': 'Mäßige Turbulenzen voraus möglich (~{0} km)',
  'No turbulence reported or forecast on the route ahead': 'Keine Turbulenzen gemeldet oder vorhergesagt', 'Turbulence info unavailable': 'Turbulenzdaten nicht verfügbar', 'Checking route ahead…': 'Strecke voraus wird geprüft…',
  'Wind': 'Wind', 'Headwind {0} kt': 'Gegenwind {0} kt', 'Tailwind {0} kt': 'Rückenwind {0} kt', 'No significant head/tailwind': 'Kein nennenswerter Gegen-/Rückenwind', '~{0}% of tank left (est., incl. reserve)': '~{0} % Resttank (geschätzt, inkl. Reserve)', 'Fuel to go (est.)': 'Restkraftstoff (geschätzt)', 'arrives {0}': 'Ankunft {0}',
  'Turbulence': 'Turbulenz', 'Turbulence advisories (SIGMET / G-AIRMET)': 'Turbulenzwarnungen (SIGMET / G-AIRMET)', 'Wind arrows': 'Windpfeile', 'Wind: FL050': 'Wind: FL050', 'Wind: FL100': 'Wind: FL100', 'Wind: FL180': 'Wind: FL180', 'Wind: FL300': 'Wind: FL300', 'Wind: FL340': 'Wind: FL340', 'Wind: FL390': 'Wind: FL390', 'Night': 'Nacht', 'Day / night': 'Tag / Nacht',
  'Wind at {0}': 'Wind auf {0}', 'Wind data unavailable': 'Winddaten nicht verfügbar', 'Turbulence data unavailable': 'Turbulenzdaten nicht verfügbar', 'Moderate turbulence': 'Mäßige Turbulenz', 'Severe turbulence': 'Starke Turbulenz', 'No turbulence advisories right now': 'Derzeit keine Turbulenzwarnungen',
  'Aircraft': 'Flugzeuge', '{0} s ago': 'vor {0} s', '{0} min ago': 'vor {0} Min.',
  'Standard': 'Standard', 'Light': 'Hell', 'Dark': 'Dunkel', 'Filters': 'Filter', 'Altitude': 'Flughöhe', 'Min speed': 'Mindestgeschw.', 'Airport': 'Flughafen',
  'Departure': 'Abflug', 'Arrival': 'Ankunft', 'Departure ↔ arrival': 'Abflug ↔ Ankunft', 'Airline': 'Fluggesellschaft', 'e.g. THY, Pegasus, Lufthansa': 'z. B. Lufthansa, Eurowings, Condor',
  'Aircraft type': 'Flugzeugtyp', 'e.g. B738, A320, boeing 777': 'z. B. B738, A320, Boeing 777', 'Show aircraft on the ground': 'Flugzeuge am Boden anzeigen',
  'Favorites only ★': 'Nur Favoriten ★', 'Search callsign or registration…': 'Rufzeichen oder Kennzeichen suchen…',
  '● Live': '● Live', 'history': 'Verlauf', 'min': 'min', 'max': 'max', ' min': ' Min.', ' h ': ' Std. ',
  'on ground': 'am Boden', 'landed': 'gelandet', 'Close': 'Schließen', 'Open photo': 'Foto öffnen', 'Previous photo': 'Vorheriges Foto', 'Next photo': 'Nächstes Foto', 'Photo': 'Foto',
  '{0} entered the alert zone': '{0} hat die Alarmzone betreten', 'loading…': 'lädt…', 'error': 'Fehler', 'last updated': 'zuletzt aktualisiert',
  'wide view: center only, zoom in': 'Weitwinkel: nur Mitte, bitte hineinzoomen', 'demo (30x speed)': 'Demo (30-fache Geschwindigkeit)', 'FLIGHTS': 'FLÜGE',
  'loading route info · {0} / {1} aircraft': 'Routen werden geladen · {0} / {1} Flugzeuge', 'Click the map to set the zone center': 'Klicke auf die Karte, um den Zonenmittelpunkt zu setzen',
  'Alert zone set ({0} km)': 'Alarmzone gesetzt ({0} km)', '{0} km flown · {1} km to go': '{0} km geflogen · noch {1} km',
  'Registration': 'Kennzeichen', 'Speed': 'Geschwindigkeit', 'Heading': 'Kurs', 'Vertical speed': 'Vertikalgeschwindigkeit', 'Nearest airport': 'Nächster Flughafen', 'Position': 'Position', 'Owner': 'Halter',
  '★ Favorited': '★ Favorit', '☆ Favorite': '☆ Favorit', 'Loading route info…': 'Route wird geladen…', 'Route info not found': 'Route nicht gefunden',
  "Couldn't load route info": 'Route konnte nicht geladen werden', 'ICAO24': 'ICAO24', 'Squawk': 'Squawk', 'Category': 'Kategorie', 'Country': 'Land',
  "Couldn't load airport info": 'Flughafendaten konnten nicht geladen werden', 'Loading…': 'Lädt…', 'Open on Wikipedia': 'Auf Wikipedia öffnen', 'Feels like': 'Gefühlt', 'Gusts': 'Böen',
  'Humidity': 'Feuchte', 'Pressure': 'Luftdruck', 'Visibility': 'Sicht', 'Arrivals': 'Ankünfte', 'Departures': 'Abflüge', 'Weather unavailable': 'Wetter nicht verfügbar',
  'Loading weather…': 'Wetter wird geladen…', 'No aircraft loaded yet': 'Noch keine Flugzeuge geladen', 'No arrivals found nearby': 'Keine Ankünfte in der Nähe', 'No departures found nearby': 'Keine Abflüge in der Nähe',
  'Clear sky': 'Klar', 'Mostly clear': 'Überwiegend klar', 'Partly cloudy': 'Teils bewölkt', 'Overcast': 'Bedeckt', 'Fog': 'Nebel', 'Freezing fog': 'Gefrierender Nebel', 'Light drizzle': 'Leichter Nieselregen',
  'Drizzle': 'Nieselregen', 'Heavy drizzle': 'Starker Nieselregen', 'Freezing drizzle': 'Gefrierender Nieselregen', 'Light rain': 'Leichter Regen', 'Rain': 'Regen', 'Heavy rain': 'Starker Regen',
  'Freezing rain': 'Gefrierender Regen', 'Light snow': 'Leichter Schneefall', 'Snow': 'Schnee', 'Heavy snow': 'Starker Schneefall', 'Snow grains': 'Schneegriesel', 'Rain showers': 'Regenschauer', 'Violent showers': 'Heftige Schauer',
  'Snow showers': 'Schneeschauer', 'Thunderstorm': 'Gewitter', 'Thunderstorm, hail': 'Gewitter mit Hagel',
  'Hijacking': 'Entführung', 'Radio failure': 'Funkausfall', 'General emergency': 'Allgemeiner Notfall', 'Emergency': 'Notfall', 'What does this code mean?': 'Was bedeutet dieser Code?',
  '{0} landed': '{0} ist gelandet', '{0} took off': '{0} ist gestartet', 'Watching {0}: you will be notified when it takes off or lands': '{0} wird beobachtet: Du erhältst eine Meldung bei Start und Landung',
  'Watchlist': 'Beobachtungsliste', 'last seen {0} min ago': 'zuletzt vor {0} Min. gesehen', 'not seen yet': 'noch nicht gesehen', 'Remove': 'Entfernen', 'Not on the map right now': 'Gerade nicht auf der Karte',
  '🔔 Watching': '🔔 Beobachtet', '🔔 Watch': '🔔 Beobachten', "Today's flights": 'Heutige Flüge', "Couldn't load today's flights": 'Heutige Flüge konnten nicht geladen werden',
  'No flights recorded today': 'Heute keine Flüge aufgezeichnet', 'in flight': 'in der Luft', 'now': 'jetzt', 'Radar unavailable': 'Radar nicht verfügbar',
  'Already logged': 'Bereits eingetragen', 'new aircraft': 'neues Flugzeug', 'new type': 'neuer Typ', 'Logged {0}': '{0} eingetragen', 'Logbook': 'Logbuch', 'aircraft': 'Flugzeuge', 'types': 'Typen',
  'airlines': 'Airlines', 'Open logbook': 'Logbuch öffnen', 'Export CSV': 'CSV exportieren', 'The logbook is empty': 'Das Logbuch ist leer', 'Search the logbook…': 'Im Logbuch suchen…',
  'Nothing matches': 'Keine Treffer', 'The logbook is empty. Open a flight and press “Log sighting”.': 'Das Logbuch ist leer. Öffne einen Flug und tippe auf „Sichtung eintragen“.',
  'NEW AIRCRAFT': 'NEUES FLUGZEUG', 'NEW TYPE': 'NEUER TYP', '✓ Logged': '✓ Eingetragen', '📓 Log sighting': '📓 Sichtung eintragen',
  'Vert. speed': 'Steigrate', 'SkyTrack keeps running in the tray when you close the window': 'SkyTrack läuft im Hintergrund im Infobereich weiter, wenn du das Fenster schließt', '📓 Flight diary': '📓 Flugtagebuch',
  'Keep running in the tray': 'Im Infobereich weiterlaufen', 'Desktop notifications': 'Desktop-Benachrichtigungen', 'Flight diary': 'Flugtagebuch', 'Flights': 'Flüge', 'Distance': 'Strecke', 'Around the Earth': 'Erdumrundungen',
  '(est.)': '(geschätzt)', 'From': 'Von', 'To': 'Nach', 'Flight no.': 'Flugnr.', 'Add': 'Hinzufügen',
  'Your diary is empty. Add a flight above, or open a flight on the map and press “Add to diary”.': 'Dein Tagebuch ist leer. Füge oben einen Flug hinzu oder öffne einen Flug auf der Karte und tippe auf „Zum Tagebuch“.',
  'Unknown airport: use an IATA or ICAO code, e.g. IST or LTFM': 'Unbekannter Flughafen: IATA- oder ICAO-Code verwenden, z. B. FRA oder EDDF', 'Share image': 'Bild teilen', 'Add to diary': 'Zum Tagebuch', 'Added to your diary': 'Zum Tagebuch hinzugefügt',
  'Free flight tracker · no account, no ads': 'Kostenloser Flugtracker · ohne Konto, ohne Werbung', 'Image saved and copied to the clipboard': 'Bild gespeichert und in die Zwischenablage kopiert', 'Image saved': 'Bild gespeichert', 'Altitude & speed': 'Höhe & Geschwindigkeit',
  'Landing': 'Im Landeanflug', 'Approaching': 'Nähert sich', 'Departed': 'Gestartet', 'En route': 'Unterwegs'
};
DICT.fr = {
  'Close menu': 'Fermer le menu', 'Open menu': 'Ouvrir le menu', 'Mode': 'Mode', 'Normal': 'Normal', 'Plane spotter': 'Spotter', 'Data': 'Données', 'Demo': 'Démo', 'Live': 'En direct',
  'Map': 'Carte', 'Airports': 'Aéroports', 'Alert zone': "Zone d'alerte", 'Radar': 'Radar', 'Rain radar': 'Radar de pluie', 'Zone radius': 'Rayon de la zone',
  'High turbulence risk ahead (~{0} km)': 'Risque élevé de turbulences devant (~{0} km)', 'Moderate turbulence possible ahead (~{0} km)': 'Turbulences modérées possibles devant (~{0} km)',
  'No turbulence reported or forecast on the route ahead': 'Aucune turbulence signalée ou prévue sur la route', 'Turbulence info unavailable': 'Infos turbulences indisponibles', 'Checking route ahead…': 'Vérification de la route…',
  'Wind': 'Vent', 'Headwind {0} kt': 'Vent de face {0} kt', 'Tailwind {0} kt': 'Vent arrière {0} kt', 'No significant head/tailwind': 'Pas de vent de face/arrière notable', '~{0}% of tank left (est., incl. reserve)': '~{0} % du réservoir restant (est., réserve incluse)', 'Fuel to go (est.)': 'Carburant restant (est.)', 'arrives {0}': 'arrivée {0}',
  'Turbulence': 'Turbulences', 'Turbulence advisories (SIGMET / G-AIRMET)': 'Avis de turbulences (SIGMET / G-AIRMET)', 'Wind arrows': 'Flèches de vent', 'Wind: FL050': 'Vent : FL050', 'Wind: FL100': 'Vent : FL100', 'Wind: FL180': 'Vent : FL180', 'Wind: FL300': 'Vent : FL300', 'Wind: FL340': 'Vent : FL340', 'Wind: FL390': 'Vent : FL390', 'Night': 'Nuit', 'Day / night': 'Jour / nuit',
  'Wind at {0}': 'Vent à {0}', 'Wind data unavailable': 'Données de vent indisponibles', 'Turbulence data unavailable': 'Données de turbulences indisponibles', 'Moderate turbulence': 'Turbulences modérées', 'Severe turbulence': 'Fortes turbulences', 'No turbulence advisories right now': 'Aucun avis de turbulences pour le moment',
  'Aircraft': 'Avions', '{0} s ago': 'il y a {0} s', '{0} min ago': 'il y a {0} min',
  'Standard': 'Standard', 'Light': 'Clair', 'Dark': 'Sombre', 'Filters': 'Filtres', 'Altitude': 'Altitude', 'Min speed': 'Vitesse min.', 'Airport': 'Aéroport',
  'Departure': 'Départ', 'Arrival': 'Arrivée', 'Departure ↔ arrival': 'Départ ↔ arrivée', 'Airline': 'Compagnie', 'e.g. THY, Pegasus, Lufthansa': 'p. ex. Air France, Transavia, Lufthansa',
  'Aircraft type': "Type d'appareil", 'e.g. B738, A320, boeing 777': 'p. ex. B738, A320, boeing 777', 'Show aircraft on the ground': 'Afficher les avions au sol',
  'Favorites only ★': 'Favoris uniquement ★', 'Search callsign or registration…': "Rechercher un indicatif ou une immatriculation…",
  '● Live': '● Direct', 'history': 'historique', 'min': 'min', 'max': 'max', ' min': ' min', ' h ': ' h ',
  'on ground': 'au sol', 'landed': 'atterri', 'Close': 'Fermer', 'Open photo': 'Ouvrir la photo', 'Previous photo': 'Photo précédente', 'Next photo': 'Photo suivante', 'Photo': 'Photo',
  '{0} entered the alert zone': '{0} est entré dans la zone d\'alerte', 'loading…': 'chargement…', 'error': 'erreur', 'last updated': 'dernière mise à jour',
  'wide view: center only, zoom in': 'vue large : centre seulement, zoomez', 'demo (30x speed)': 'démo (vitesse ×30)', 'FLIGHTS': 'VOLS',
  'loading route info · {0} / {1} aircraft': 'chargement des routes · {0} / {1} avions', 'Click the map to set the zone center': 'Cliquez sur la carte pour placer le centre de la zone',
  'Alert zone set ({0} km)': "Zone d'alerte définie ({0} km)", '{0} km flown · {1} km to go': '{0} km parcourus · {1} km restants',
  'Registration': 'Immatriculation', 'Speed': 'Vitesse', 'Heading': 'Cap', 'Vertical speed': 'Vitesse verticale', 'Nearest airport': 'Aéroport le plus proche', 'Position': 'Position', 'Owner': 'Propriétaire',
  '★ Favorited': '★ Favori', '☆ Favorite': '☆ Favori', 'Loading route info…': 'Chargement de la route…', 'Route info not found': 'Route introuvable',
  "Couldn't load route info": 'Impossible de charger la route', 'ICAO24': 'ICAO24', 'Squawk': 'Squawk', 'Category': 'Catégorie', 'Country': 'Pays',
  "Couldn't load airport info": "Impossible de charger les infos de l'aéroport", 'Loading…': 'Chargement…', 'Open on Wikipedia': 'Ouvrir sur Wikipédia', 'Feels like': 'Ressenti', 'Gusts': 'Rafales',
  'Humidity': 'Humidité', 'Pressure': 'Pression', 'Visibility': 'Visibilité', 'Arrivals': 'Arrivées', 'Departures': 'Départs', 'Weather unavailable': 'Météo indisponible',
  'Loading weather…': 'Chargement de la météo…', 'No aircraft loaded yet': "Aucun avion chargé pour l'instant", 'No arrivals found nearby': 'Aucune arrivée à proximité', 'No departures found nearby': 'Aucun départ à proximité',
  'Clear sky': 'Ciel dégagé', 'Mostly clear': 'Plutôt dégagé', 'Partly cloudy': 'Partiellement nuageux', 'Overcast': 'Couvert', 'Fog': 'Brouillard', 'Freezing fog': 'Brouillard givrant', 'Light drizzle': 'Bruine légère',
  'Drizzle': 'Bruine', 'Heavy drizzle': 'Bruine forte', 'Freezing drizzle': 'Bruine verglaçante', 'Light rain': 'Pluie légère', 'Rain': 'Pluie', 'Heavy rain': 'Forte pluie',
  'Freezing rain': 'Pluie verglaçante', 'Light snow': 'Neige légère', 'Snow': 'Neige', 'Heavy snow': 'Forte neige', 'Snow grains': 'Grains de neige', 'Rain showers': 'Averses', 'Violent showers': 'Fortes averses',
  'Snow showers': 'Averses de neige', 'Thunderstorm': 'Orage', 'Thunderstorm, hail': 'Orage avec grêle',
  'Hijacking': 'Détournement', 'Radio failure': 'Panne radio', 'General emergency': 'Urgence générale', 'Emergency': 'Urgence', 'What does this code mean?': 'Que signifie ce code ?',
  '{0} landed': '{0} a atterri', '{0} took off': '{0} a décollé', 'Watching {0}: you will be notified when it takes off or lands': '{0} suivi : vous serez prévenu au décollage et à l\'atterrissage',
  'Watchlist': 'Liste de suivi', 'last seen {0} min ago': 'vu il y a {0} min', 'not seen yet': 'pas encore vu', 'Remove': 'Retirer', 'Not on the map right now': 'Pas sur la carte pour le moment',
  '🔔 Watching': '🔔 Suivi', '🔔 Watch': '🔔 Suivre', "Today's flights": "Vols d'aujourd'hui", "Couldn't load today's flights": "Impossible de charger les vols d'aujourd'hui",
  'No flights recorded today': "Aucun vol enregistré aujourd'hui", 'in flight': 'en vol', 'now': 'maintenant', 'Radar unavailable': 'Radar indisponible',
  'Already logged': 'Déjà enregistré', 'new aircraft': 'nouvel avion', 'new type': 'nouveau type', 'Logged {0}': '{0} enregistré', 'Logbook': 'Carnet', 'aircraft': 'avions', 'types': 'types',
  'airlines': 'compagnies', 'Open logbook': 'Ouvrir le carnet', 'Export CSV': 'Exporter en CSV', 'The logbook is empty': 'Le carnet est vide', 'Search the logbook…': 'Rechercher dans le carnet…',
  'Nothing matches': 'Aucun résultat', 'The logbook is empty. Open a flight and press “Log sighting”.': 'Le carnet est vide. Ouvrez un vol et appuyez sur « Noter l\'observation ».',
  'NEW AIRCRAFT': 'NOUVEL AVION', 'NEW TYPE': 'NOUVEAU TYPE', '✓ Logged': '✓ Enregistré', '📓 Log sighting': "📓 Noter l'observation",
  'Vert. speed': 'Vit. verticale', 'SkyTrack keeps running in the tray when you close the window': "SkyTrack continue de tourner dans la zone de notification à la fermeture de la fenêtre", '📓 Flight diary': '📓 Carnet de vols',
  'Keep running in the tray': 'Rester actif dans la zone de notification', 'Desktop notifications': 'Notifications de bureau', 'Flight diary': 'Carnet de vols', 'Flights': 'Vols', 'Distance': 'Distance', 'Around the Earth': 'Tours du monde',
  '(est.)': '(est.)', 'From': 'De', 'To': 'Vers', 'Flight no.': 'N° de vol', 'Add': 'Ajouter',
  'Your diary is empty. Add a flight above, or open a flight on the map and press “Add to diary”.': 'Votre carnet est vide. Ajoutez un vol ci-dessus ou ouvrez-en un sur la carte et appuyez sur « Ajouter au carnet ».',
  'Unknown airport: use an IATA or ICAO code, e.g. IST or LTFM': 'Aéroport inconnu : utilisez un code IATA ou OACI, p. ex. CDG ou LFPG', 'Share image': "Partager l'image", 'Add to diary': 'Ajouter au carnet', 'Added to your diary': 'Ajouté à votre carnet',
  'Free flight tracker · no account, no ads': 'Suivi de vols gratuit · sans compte, sans pub', 'Image saved and copied to the clipboard': 'Image enregistrée et copiée dans le presse-papiers', 'Image saved': 'Image enregistrée', 'Altitude & speed': 'Altitude et vitesse',
  'Landing': "En approche finale", 'Approaching': "En approche", 'Departed': 'Parti', 'En route': 'En route'
};
