// Arabic, Chinese (Simplified), Japanese and Korean UI texts (keys are the English texts, same as the other tables). Missing keys fall back to English.

DICT.ar = {
  "Close menu": "إغلاق القائمة",
  "Open menu": "فتح القائمة",
  "Mode": "الوضع",
  "Normal": "عادي",
  "Plane spotter": "راصد الطائرات",
  "Data": "البيانات",
  "Demo": "تجريبي",
  "Live": "مباشر",
  "Map": "الخريطة",
  "Airports": "المطارات",
  "Alert zone": "منطقة التنبيه",
  "Radar": "الرادار",
  "Rain radar": "رادار الأمطار",
  "Zone radius": "نصف قطر المنطقة",
  "High turbulence risk ahead (~{0} km)": "احتمال مرتفع لاضطراب جوي في الأمام (~{0} كم)",
  "Moderate turbulence possible ahead (~{0} km)": "احتمال اضطراب جوي متوسط في الأمام (~{0} كم)",
  "No turbulence reported or forecast on the route ahead": "لا توجد بلاغات أو توقعات باضطراب جوي على المسار الأمامي",
  "Turbulence info unavailable": "معلومات الاضطراب الجوي غير متاحة",
  "Checking route ahead…": "جارٍ فحص المسار الأمامي…",
  "Wind": "الرياح",
  "Headwind {0} kt": "رياح معاكسة {0} عقدة",
  "Tailwind {0} kt": "رياح خلفية {0} عقدة",
  "No significant head/tailwind": "لا رياح معاكسة أو خلفية ملحوظة",
  "~{0}% of tank left (est., incl. reserve)": "متبقٍ ~{0}% من الخزان (تقديري، مع الاحتياطي)",
  "Fuel to go (est.)": "الوقود المتبقي (تقديري)",
  "arrives {0}": "تصل {0}",
  "Turbulence": "الاضطراب الجوي",
  "Turbulence advisories (SIGMET / G-AIRMET)": "تحذيرات الاضطراب الجوي (SIGMET / G-AIRMET)",
  "Wind arrows": "أسهم الرياح",
  "Wind: FL050": "الرياح: FL050",
  "Wind: FL100": "الرياح: FL100",
  "Wind: FL180": "الرياح: FL180",
  "Wind: FL300": "الرياح: FL300",
  "Wind: FL340": "الرياح: FL340",
  "Wind: FL390": "الرياح: FL390",
  "Night": "الليل",
  "Day / night": "النهار / الليل",
  "Wind at {0}": "الرياح عند {0}",
  "Wind data unavailable": "بيانات الرياح غير متاحة",
  "Turbulence data unavailable": "بيانات الاضطراب الجوي غير متاحة",
  "Moderate turbulence": "اضطراب جوي متوسط",
  "Severe turbulence": "اضطراب جوي شديد",
  "No turbulence advisories right now": "لا توجد تحذيرات اضطراب جوي حاليًا",
  "Aircraft": "الطائرات",
  "{0} s ago": "قبل {0} ث",
  "{0} min ago": "قبل {0} د",
  "Standard": "قياسي",
  "Light": "فاتح",
  "Dark": "داكن",
  "Filters": "التصفية",
  "Altitude": "الارتفاع",
  "Min speed": "أدنى سرعة",
  "Airport": "المطار",
  "Departure": "المغادرة",
  "Arrival": "الوصول",
  "Departure ↔ arrival": "المغادرة ↔ الوصول",
  "Airline": "شركة الطيران",
  "e.g. THY, Pegasus, Lufthansa": "مثال: THY أو Pegasus أو Lufthansa",
  "Aircraft type": "نوع الطائرة",
  "e.g. B738, A320, boeing 777": "مثال: B738 أو A320 أو boeing 777",
  "Show aircraft on the ground": "إظهار الطائرات على الأرض",
  "Favorites only ★": "المفضلة فقط ★",
  "Search callsign or registration…": "ابحث برمز النداء أو رقم التسجيل…",
  "● Live": "● مباشر",
  "history": "السجل",
  "min": "د",
  "max": "أقصى",
  " min": " د",
  " h ": " س ",
  "on ground": "على الأرض",
  "landed": "هبطت",
  "Close": "إغلاق",
  "Open photo": "فتح الصورة",
  "Previous photo": "الصورة السابقة",
  "Next photo": "الصورة التالية",
  "Photo": "صورة",
  "{0} entered the alert zone": "دخلت {0} منطقة التنبيه",
  "loading…": "جارٍ التحميل…",
  "error": "خطأ",
  "last updated": "آخر تحديث",
  "wide view: center only, zoom in": "عرض واسع: المركز فقط، قرّب للمزيد",
  "demo (30x speed)": "تجريبي (سرعة ×30)",
  "FLIGHTS": "الرحلات",
  "loading route info · {0} / {1} aircraft": "جارٍ تحميل معلومات المسار · {0} / {1} طائرة",
  "Click the map to set the zone center": "انقر على الخريطة لتحديد مركز المنطقة",
  "Alert zone set ({0} km)": "تم تحديد منطقة التنبيه ({0} كم)",
  "{0} km flown · {1} km to go": "{0} كم مقطوعة · {1} كم متبقية",
  "Registration": "التسجيل",
  "Speed": "السرعة",
  "Heading": "الاتجاه",
  "Vertical speed": "السرعة الرأسية",
  "Nearest airport": "أقرب مطار",
  "Position": "الموقع",
  "Owner": "المالك",
  "★ Favorited": "★ في المفضلة",
  "☆ Favorite": "☆ أضف للمفضلة",
  "Loading route info…": "جارٍ تحميل معلومات المسار…",
  "Route info not found": "لم يتم العثور على معلومات المسار",
  "Couldn't load route info": "تعذّر تحميل معلومات المسار",
  "ICAO24": "ICAO24",
  "Squawk": "Squawk",
  "Category": "الفئة",
  "Country": "الدولة",
  "Couldn't load airport info": "تعذّر تحميل معلومات المطار",
  "Loading…": "جارٍ التحميل…",
  "Open on Wikipedia": "فتح في ويكيبيديا",
  "Feels like": "الإحساس",
  "Gusts": "هبّات",
  "Humidity": "الرطوبة",
  "Pressure": "الضغط",
  "Visibility": "مدى الرؤية",
  "Arrivals": "الوصول",
  "Departures": "المغادرة",
  "Weather unavailable": "الطقس غير متاح",
  "Loading weather…": "جارٍ تحميل الطقس…",
  "No aircraft loaded yet": "لم تُحمَّل أي طائرة بعد",
  "No arrivals found nearby": "لا توجد رحلات وصول قريبة",
  "No departures found nearby": "لا توجد رحلات مغادرة قريبة",
  "Clear sky": "سماء صافية",
  "Mostly clear": "صافية غالبًا",
  "Partly cloudy": "غائم جزئيًا",
  "Overcast": "غائم",
  "Fog": "ضباب",
  "Freezing fog": "ضباب متجمد",
  "Light drizzle": "رذاذ خفيف",
  "Drizzle": "رذاذ",
  "Heavy drizzle": "رذاذ كثيف",
  "Freezing drizzle": "رذاذ متجمد",
  "Light rain": "مطر خفيف",
  "Rain": "مطر",
  "Heavy rain": "مطر غزير",
  "Freezing rain": "مطر متجمد",
  "Light snow": "ثلج خفيف",
  "Snow": "ثلج",
  "Heavy snow": "ثلج كثيف",
  "Snow grains": "حبيبات ثلج",
  "Rain showers": "زخات مطر",
  "Violent showers": "زخات عنيفة",
  "Snow showers": "زخات ثلج",
  "Thunderstorm": "عاصفة رعدية",
  "Thunderstorm, hail": "عاصفة رعدية مع برد",
  "Hijacking": "اختطاف",
  "Radio failure": "عطل في الراديو",
  "General emergency": "طوارئ عامة",
  "Emergency": "طوارئ",
  "What does this code mean?": "ماذا يعني هذا الرمز؟",
  "{0} landed": "هبطت {0}",
  "{0} took off": "أقلعت {0}",
  "Watching {0}: you will be notified when it takes off or lands": "تتم مراقبة {0}: ستصلك إشعارات عند إقلاعها أو هبوطها",
  "Watchlist": "قائمة المراقبة",
  "last seen {0} min ago": "شوهدت آخر مرة قبل {0} د",
  "not seen yet": "لم تُشاهد بعد",
  "Remove": "إزالة",
  "Not on the map right now": "ليست على الخريطة الآن",
  "🔔 Watching": "🔔 قيد المراقبة",
  "🔔 Watch": "🔔 راقب",
  "Today's flights": "رحلات اليوم",
  "Couldn't load today's flights": "تعذّر تحميل رحلات اليوم",
  "No flights recorded today": "لا توجد رحلات مسجلة اليوم",
  "in flight": "في الجو",
  "now": "الآن",
  "Radar unavailable": "الرادار غير متاح",
  "Already logged": "سُجّلت من قبل",
  "new aircraft": "طائرة جديدة",
  "new type": "نوع جديد",
  "Logged {0}": "تم تسجيل {0}",
  "Logbook": "سجل المشاهدات",
  "aircraft": "طائرات",
  "types": "أنواع",
  "airlines": "شركات طيران",
  "Open logbook": "فتح السجل",
  "Export CSV": "تصدير CSV",
  "The logbook is empty": "السجل فارغ",
  "Search the logbook…": "ابحث في السجل…",
  "Nothing matches": "لا توجد نتائج مطابقة",
  "The logbook is empty. Open a flight and press “Log sighting”.": "السجل فارغ. افتح رحلة واضغط «تسجيل مشاهدة».",
  "NEW AIRCRAFT": "طائرة جديدة",
  "NEW TYPE": "نوع جديد",
  "✓ Logged": "✓ تم التسجيل",
  "📓 Log sighting": "📓 تسجيل مشاهدة",
  "Vert. speed": "السرعة الرأسية",
  "SkyTrack keeps running in the tray when you close the window": "يستمر SkyTrack في العمل في الشريط عند إغلاق النافذة",
  "📓 Flight diary": "📓 مفكرة الرحلات",
  "Keep running in the tray": "الاستمرار في العمل في شريط المهام",
  "Desktop notifications": "إشعارات سطح المكتب",
  "In-app notifications": "الإشعارات داخل التطبيق",
  "Flight diary": "مفكرة الرحلات",
  "Flights": "الرحلات",
  "Distance": "المسافة",
  "Around the Earth": "حول الأرض",
  "(est.)": "(تقديري)",
  "From": "من",
  "To": "إلى",
  "Flight no.": "رقم الرحلة",
  "Add": "إضافة",
  "Your diary is empty. Add a flight above, or open a flight on the map and press “Add to diary”.": "مفكرتك فارغة. أضف رحلة أعلاه، أو افتح رحلة على الخريطة واضغط «إضافة إلى المفكرة».",
  "Unknown airport: use an IATA or ICAO code, e.g. IST or LTFM": "مطار غير معروف: استخدم رمز IATA أو ICAO، مثل IST أو LTFM",
  "Share image": "مشاركة صورة",
  "Add to diary": "إضافة إلى المفكرة",
  "Added to your diary": "أُضيفت إلى مفكرتك",
  "Free flight tracker · no account, no ads": "متتبع رحلات مجاني · بلا حساب وبلا إعلانات",
  "Image saved and copied to the clipboard": "تم حفظ الصورة ونسخها إلى الحافظة",
  "Image saved": "تم حفظ الصورة",
  "Altitude & speed": "الارتفاع والسرعة",
  "Landing": "هبوط",
  "Approaching": "اقتراب",
  "Departed": "أقلعت",
  "En route": "في الطريق",
  "A free flight tracker: no account, no ads. Here is a quick tour of what you can do.": "متتبع رحلات مجاني: بلا حساب وبلا إعلانات. إليك جولة سريعة فيما يمكنك فعله.",
  "Aircraft within {0} of your spot": "الطائرات ضمن {0} من موقعك",
  "Airline code": "رمز شركة الطيران",
  "Airport code": "رمز المطار",
  "Alert zone set ({0})": "تم تحديد منطقة التنبيه ({0})",
  "Alerts": "التنبيهات",
  "App": "التطبيق",
  "Back": "رجوع",
  "Callsign contains": "رمز النداء يحتوي على",
  "Choose where you are": "اختر مكانك",
  "Click a plane to see its route, photo, altitude, speed and more. Click an airport (yellow dot) for its weather and arrivals.": "انقر على طائرة لترى مسارها وصورتها وارتفاعها وسرعتها وغير ذلك. انقر على مطار (النقطة الصفراء) لترى طقسه ورحلاته.",
  "Click any aircraft": "انقر على أي طائرة",
  "Click the map to set your spot": "انقر على الخريطة لتحديد موقعك",
  "Click the map where you are, or type an airport code. SkyTrack lists the aircraft flying around that spot, with the direction to look and how high in the sky.": "انقر على الخريطة حيث تقف، أو اكتب رمز مطار. يعرض SkyTrack الطائرات المحلقة حول موقعك، مع اتجاه النظر وارتفاعها في السماء.",
  "Click the map": "انقر على الخريطة",
  "Move my spot": "تحريك موقعي",
  "Done": "تم",
  "Next": "التالي",
  "Download": "تنزيل",
  "Downloading update {0}…": "جارٍ تنزيل التحديث {0}…",
  "Get a notification when an aircraft you care about shows up on the map.": "احصل على إشعار عند ظهور طائرة تهمّك على الخريطة.",
  "Headwind {0}": "رياح معاكسة {0}",
  "Tailwind {0}": "رياح خلفية {0}",
  "Helicopters": "المروحيات",
  "Hide or show the menu any time. Enjoy the sky!": "يمكنك إخفاء القائمة أو إظهارها في أي وقت. استمتع بالسماء!",
  "High turbulence risk ahead (~{0})": "احتمال مرتفع لاضطراب جوي في الأمام (~{0})",
  "Moderate turbulence possible ahead (~{0})": "احتمال اضطراب جوي متوسط في الأمام (~{0})",
  "Keep a flight diary, set alerts for rare aircraft, see what is flying overhead, and change units in Settings.": "دوّن مفكرة رحلات، واضبط تنبيهات للطائرات النادرة، وشاهد ما يحلّق فوقك، وغيّر الوحدات من الإعدادات.",
  "Menu button": "زر القائمة",
  "Military aircraft": "الطائرات العسكرية",
  "Narrow the map by altitude, speed, airport, airline or aircraft type.": "حصر الخريطة حسب الارتفاع أو السرعة أو المطار أو شركة الطيران أو نوع الطائرة.",
  "New version {0} available": "الإصدار الجديد {0} متاح",
  "No alerts yet. Add one above.": "لا توجد تنبيهات بعد. أضف تنبيهًا أعلاه.",
  "Nothing overhead right now.": "لا شيء فوقك الآن.",
  "Overhead": "فوقي",
  "Radius": "نصف القطر",
  "Restart": "إعادة التشغيل",
  "Search the whole world": "ابحث في العالم كله",
  "Settings": "الإعدادات",
  "Show the tour again": "عرض الجولة مرة أخرى",
  "Skip": "تخطّي",
  "Switch the whole app between English, Turkish, Spanish, German and French.": "بدّل لغة التطبيق بالكامل بين الإنجليزية والتركية والإسبانية والألمانية والفرنسية والعربية والصينية واليابانية والكورية.",
  "Temperature": "درجة الحرارة",
  "Time": "الوقت",
  "Type a callsign, registration, aircraft type or airport. Results are not limited to the part of the map you see.": "اكتب رمز نداء أو رقم تسجيل أو نوع طائرة أو مطارًا. النتائج لا تقتصر على الجزء الظاهر من الخريطة.",
  "Units": "الوحدات",
  "Update {0} is ready": "التحديث {0} جاهز",
  "Welcome to SkyTrack": "مرحبًا بك في SkyTrack",
  "Worldwide": "حول العالم",
  "Your language": "لغتك",
  "Your tools": "أدواتك",
  "e.g. A388, THY, TC-JNA": "مثال: A388 أو THY أو TC-JNA",
  "{0} flown · {1} to go": "{0} مقطوعة · {1} متبقية",
  "{0} more aircraft match your alerts": "{0} طائرات أخرى تطابق تنبيهاتك",
  "⚙ Settings": "⚙ الإعدادات",
  "📍 Overhead": "📍 فوقي",
  "🔔 Alerts": "🔔 التنبيهات",
  "A free OpenSky API client gives the wide view a much higher daily limit. Create one in your OpenSky account. It is stored encrypted on this computer.": "يمنح عميل OpenSky API المجاني العرض الواسع حدًا يوميًا أعلى بكثير. أنشئ واحدًا في حسابك على OpenSky. يُخزَّن مشفّرًا على هذا الجهاز.",
  "Aircraft trails": "مسارات الطائرات",
  "Based on the aircraft SkyTrack has loaded around the map.": "استنادًا إلى الطائرات التي حمّلها SkyTrack حول الخريطة.",
  "Busiest airports": "أكثر المطارات ازدحامًا",
  "Clouds": "السحب",
  "Connected as {0}": "متصل باسم {0}",
  "Could not store the credentials": "تعذّر حفظ بيانات الاعتماد",
  "Data sources are busy, retrying shortly. Showing the last known positions.": "مصادر البيانات مشغولة، ستُعاد المحاولة قريبًا. يتم عرض آخر المواقع المعروفة.",
  "Fastest": "الأسرع",
  "Highest": "الأعلى",
  "How far back you can rewind": "إلى أي مدى يمكنك الرجوع للخلف",
  "In the air": "في الجو",
  "No connection to the data sources. Showing the last known positions.": "لا يوجد اتصال بمصادر البيانات. يتم عرض آخر المواقع المعروفة.",
  "On the ground": "على الأرض",
  "OpenSky account (optional)": "حساب OpenSky (اختياري)",
  "Replay history": "إعادة تشغيل السجل",
  "Satellite imagery with clouds (NASA, latest daily image)": "صور الأقمار الصناعية مع السحب (ناسا، أحدث صورة يومية)",
  "Save": "حفظ",
  "Stats": "الإحصاءات",
  "Top aircraft types": "أكثر أنواع الطائرات",
  "Top airlines": "أكثر شركات الطيران",
  "Trails": "المسارات",
  "You can also try Demo mode.": "يمكنك أيضًا تجربة الوضع التجريبي.",
  "{0} aircraft with an emergency code": "{0} طائرات برمز طوارئ",
  "📊 Stats": "📊 الإحصاءات",
  "OpenSky account saved": "تم حفظ حساب OpenSky",
  "1) Sign up at opensky-network.org (free)  2) Account page → create an API client  3) Paste Client ID and secret here.": "1) سجّل في opensky-network.org (مجانًا)  2) من صفحة الحساب أنشئ عميل API  3) الصق Client ID والسر هنا.",
  "Open OpenSky account page": "فتح صفحة حساب OpenSky",
  "Tip: add a free OpenSky account in Settings to fill the wide view": "نصيحة: أضف حساب OpenSky مجانيًا من الإعدادات لملء العرض الواسع",
  "OpenSky account removed": "تمت إزالة حساب OpenSky",
  "Check for updates": "التحقق من التحديثات",
  "Checking…": "جارٍ التحقق…",
  "You are up to date.": "أنت على أحدث إصدار.",
  "Version {0} found, downloading…": "تم العثور على الإصدار {0}، جارٍ التنزيل…",
  "Could not check for updates: {0}": "تعذّر التحقق من التحديثات: {0}",
  "Version {0} is available: use the bar at the bottom of the menu.": "الإصدار {0} متاح: استخدم الشريط أسفل القائمة.",
  "Thin ADS-B coverage here: some aircraft may be missing": "تغطية ADS-B ضعيفة هنا: قد تكون بعض الطائرات غير ظاهرة",
  "Seat tip": "نصيحة المقعد",
  "Sun side": "جهة الشمس",
  "Over the wings you feel turbulence least, the back rows most.": "فوق الجناحين تشعر بالاضطراب أقل، وفي الصفوف الخلفية أكثر.",
  "Right side": "الجهة اليمنى",
  "Left side": "الجهة اليسرى",
  "Route check": "فحص المسار",
  "🧭 Route check": "🧭 فحص المسار",
  "Is there turbulence on a route? Pick two airports to see what is reported along the way at three cruise altitudes.": "هل هناك اضطراب جوي على مسار ما؟ اختر مطارين لترى ما أُبلغ عنه في الطريق على ثلاثة ارتفاعات للتحليق.",
  "Check route": "فحص المسار",
  "Use selected flight": "استخدام الرحلة المحددة",
  "High turbulence risk": "احتمال مرتفع لاضطراب جوي",
  "Moderate turbulence possible": "احتمال اضطراب جوي متوسط",
  "Nothing reported": "لا بلاغات",
  "first about {0} from {1}": "أول مرة بعد نحو {0} من {1}",
  "Based on SIGMET / G-AIRMET advisories and pilot reports from the last 2 hours. Nothing reported is not a guarantee.": "استنادًا إلى تحذيرات SIGMET / G-AIRMET وتقارير الطيارين خلال آخر ساعتين. عدم وجود بلاغات لا يعني الضمان.",
  "Show on map": "عرض على الخريطة",
  "{0}: high turbulence risk ahead (~{1}). Keep your seat belt fastened.": "{0}: احتمال مرتفع لاضطراب جوي في الأمام (~{1}). أبقِ حزام الأمان مربوطًا.",
  "{0}: moderate turbulence possible ahead (~{1}). Keep your seat belt fastened.": "{0}: احتمال اضطراب جوي متوسط في الأمام (~{1}). أبقِ حزام الأمان مربوطًا.",
  "{0}: nothing reported on the route ahead any more": "{0}: لم يعد هناك أي بلاغ على المسار الأمامي",
  "Enter a flight number, e.g. TK1 or THY1": "أدخل رقم رحلة، مثل TK1 أو THY1",
  "Watching {0}: SkyTrack tells you when it is in the air, and about turbulence ahead": "تتم مراقبة {0}: سيُخبرك SkyTrack عندما تكون في الجو وعن أي اضطراب جوي في الأمام",
  "{0} is in the air: watching": "{0} في الجو: قيد المراقبة",
  "Watch a flight": "مراقبة رحلة",
  "Enter a flight number. You get a notification when it is in the air and when there is turbulence ahead.": "أدخل رقم رحلة. ستصلك إشعارات عندما تكون في الجو وعند وجود اضطراب جوي في الأمام.",
  "Flight number, e.g. TK1": "رقم الرحلة، مثل TK1",
  "Watch": "مراقبة",
  "waiting for departure": "بانتظار الإقلاع",
  "Copy tracking link": "نسخ رابط التتبع",
  "Tracking link copied": "تم نسخ رابط التتبع",
  "Showing {0} of {1} aircraft · zoom in for all": "يتم عرض {0} من {1} طائرة · قرّب لعرضها كلها",
  "Thin out crowded areas when zoomed out": "تقليل الازدحام عند التصغير",
  "Wide view: filling in, zoom in for all": "عرض واسع: جارٍ الملء، قرّب لعرض الكل",
  "landed {0} ago": "هبطت قبل {0}",
  "just landed": "هبطت للتو",
  "✕ Remove overhead spot": "✕ إزالة موقع «فوقي»",
  "Remove my spot": "إزالة موقعي",
  "Your spot": "موقعك",
  "Overhead spot removed": "تمت إزالة موقع «فوقي»",
  "Click to switch between the animation and the dashed line": "انقر للتبديل بين الرسوم المتحركة والخط المتقطع",
  "Download and install": "تنزيل وتثبيت",
  "Install": "تثبيت",
  "Update {0} downloaded": "تم تنزيل التحديث {0}",
  "Update download failed": "فشل تنزيل التحديث",
  "Open the download page": "فتح صفحة التنزيل",
  "The disk image was opened: drag SkyTrack to Applications": "تم فتح صورة القرص: اسحب SkyTrack إلى التطبيقات",
  "The AppImage is in your Downloads folder: make it executable and run it": "ملف AppImage في مجلد التنزيلات: اجعله قابلًا للتنفيذ وشغّله"
};

DICT.zh = {
  "Close menu": "关闭菜单",
  "Open menu": "打开菜单",
  "Mode": "模式",
  "Normal": "普通",
  "Plane spotter": "飞机观察者",
  "Data": "数据",
  "Demo": "演示",
  "Live": "实时",
  "Map": "地图",
  "Airports": "机场",
  "Alert zone": "警戒区",
  "Radar": "雷达",
  "Rain radar": "降雨雷达",
  "Zone radius": "区域半径",
  "High turbulence risk ahead (~{0} km)": "前方有高强度颠簸风险（约 {0} 公里）",
  "Moderate turbulence possible ahead (~{0} km)": "前方可能有中等颠簸（约 {0} 公里）",
  "No turbulence reported or forecast on the route ahead": "前方航路无颠簸报告或预报",
  "Turbulence info unavailable": "颠簸信息不可用",
  "Checking route ahead…": "正在检查前方航路…",
  "Wind": "风",
  "Headwind {0} kt": "逆风 {0} 节",
  "Tailwind {0} kt": "顺风 {0} 节",
  "No significant head/tailwind": "无明显顶风/顺风",
  "~{0}% of tank left (est., incl. reserve)": "油箱约剩 {0}%（估算，含备份油量）",
  "Fuel to go (est.)": "剩余燃油（估算）",
  "arrives {0}": "预计 {0} 到达",
  "Turbulence": "颠簸",
  "Turbulence advisories (SIGMET / G-AIRMET)": "颠簸警报（SIGMET / G-AIRMET）",
  "Wind arrows": "风向箭头",
  "Wind: FL050": "风：FL050",
  "Wind: FL100": "风：FL100",
  "Wind: FL180": "风：FL180",
  "Wind: FL300": "风：FL300",
  "Wind: FL340": "风：FL340",
  "Wind: FL390": "风：FL390",
  "Night": "夜间",
  "Day / night": "昼夜",
  "Wind at {0}": "{0} 高度的风",
  "Wind data unavailable": "风数据不可用",
  "Turbulence data unavailable": "颠簸数据不可用",
  "Moderate turbulence": "中等颠簸",
  "Severe turbulence": "强颠簸",
  "No turbulence advisories right now": "目前没有颠簸警报",
  "Aircraft": "飞机",
  "{0} s ago": "{0} 秒前",
  "{0} min ago": "{0} 分钟前",
  "Standard": "标准",
  "Light": "浅色",
  "Dark": "深色",
  "Filters": "筛选",
  "Altitude": "高度",
  "Min speed": "最低速度",
  "Airport": "机场",
  "Departure": "出发",
  "Arrival": "到达",
  "Departure ↔ arrival": "出发 ↔ 到达",
  "Airline": "航空公司",
  "e.g. THY, Pegasus, Lufthansa": "例如 THY、Pegasus、Lufthansa",
  "Aircraft type": "机型",
  "e.g. B738, A320, boeing 777": "例如 B738、A320、boeing 777",
  "Show aircraft on the ground": "显示地面上的飞机",
  "Favorites only ★": "仅收藏 ★",
  "Search callsign or registration…": "搜索呼号或注册号…",
  "● Live": "● 实时",
  "history": "历史",
  "min": "最小",
  "max": "最大",
  " min": " 分钟",
  " h ": " 小时 ",
  "on ground": "地面",
  "landed": "已降落",
  "Close": "关闭",
  "Open photo": "打开照片",
  "Previous photo": "上一张照片",
  "Next photo": "下一张照片",
  "Photo": "照片",
  "{0} entered the alert zone": "{0} 进入了警戒区",
  "loading…": "加载中…",
  "error": "错误",
  "last updated": "最后更新",
  "wide view: center only, zoom in": "广域视图：仅中心区域，请放大",
  "demo (30x speed)": "演示（30 倍速）",
  "FLIGHTS": "航班",
  "loading route info · {0} / {1} aircraft": "正在加载航路信息 · {0} / {1} 架飞机",
  "Click the map to set the zone center": "点击地图设置区域中心",
  "Alert zone set ({0} km)": "警戒区已设置（{0} 公里）",
  "{0} km flown · {1} km to go": "已飞 {0} 公里 · 还剩 {1} 公里",
  "Registration": "注册号",
  "Speed": "速度",
  "Heading": "航向",
  "Vertical speed": "垂直速度",
  "Nearest airport": "最近的机场",
  "Position": "位置",
  "Owner": "所有人",
  "★ Favorited": "★ 已收藏",
  "☆ Favorite": "☆ 收藏",
  "Loading route info…": "正在加载航路信息…",
  "Route info not found": "未找到航路信息",
  "Couldn't load route info": "无法加载航路信息",
  "ICAO24": "ICAO24",
  "Squawk": "应答机码",
  "Category": "类别",
  "Country": "国家",
  "Couldn't load airport info": "无法加载机场信息",
  "Loading…": "加载中…",
  "Open on Wikipedia": "在维基百科中打开",
  "Feels like": "体感温度",
  "Gusts": "阵风",
  "Humidity": "湿度",
  "Pressure": "气压",
  "Visibility": "能见度",
  "Arrivals": "到达航班",
  "Departures": "出发航班",
  "Weather unavailable": "天气不可用",
  "Loading weather…": "正在加载天气…",
  "No aircraft loaded yet": "尚未加载任何飞机",
  "No arrivals found nearby": "附近没有到达航班",
  "No departures found nearby": "附近没有出发航班",
  "Clear sky": "晴",
  "Mostly clear": "大部晴朗",
  "Partly cloudy": "局部多云",
  "Overcast": "阴",
  "Fog": "雾",
  "Freezing fog": "冻雾",
  "Light drizzle": "小毛毛雨",
  "Drizzle": "毛毛雨",
  "Heavy drizzle": "大毛毛雨",
  "Freezing drizzle": "冻毛毛雨",
  "Light rain": "小雨",
  "Rain": "雨",
  "Heavy rain": "大雨",
  "Freezing rain": "冻雨",
  "Light snow": "小雪",
  "Snow": "雪",
  "Heavy snow": "大雪",
  "Snow grains": "米雪",
  "Rain showers": "阵雨",
  "Violent showers": "强阵雨",
  "Snow showers": "阵雪",
  "Thunderstorm": "雷暴",
  "Thunderstorm, hail": "雷暴伴冰雹",
  "Hijacking": "劫机",
  "Radio failure": "无线电故障",
  "General emergency": "一般紧急情况",
  "Emergency": "紧急情况",
  "What does this code mean?": "这个代码是什么意思？",
  "{0} landed": "{0} 已降落",
  "{0} took off": "{0} 已起飞",
  "Watching {0}: you will be notified when it takes off or lands": "正在关注 {0}：起飞或降落时会通知你",
  "Watchlist": "关注列表",
  "last seen {0} min ago": "{0} 分钟前最后一次看到",
  "not seen yet": "尚未看到",
  "Remove": "移除",
  "Not on the map right now": "目前不在地图上",
  "🔔 Watching": "🔔 关注中",
  "🔔 Watch": "🔔 关注",
  "Today's flights": "今日航班",
  "Couldn't load today's flights": "无法加载今日航班",
  "No flights recorded today": "今天没有航班记录",
  "in flight": "飞行中",
  "now": "现在",
  "Radar unavailable": "雷达不可用",
  "Already logged": "已记录过",
  "new aircraft": "新飞机",
  "new type": "新机型",
  "Logged {0}": "已记录 {0}",
  "Logbook": "观测日志",
  "aircraft": "飞机",
  "types": "机型",
  "airlines": "航空公司",
  "Open logbook": "打开日志",
  "Export CSV": "导出 CSV",
  "The logbook is empty": "日志为空",
  "Search the logbook…": "搜索日志…",
  "Nothing matches": "没有匹配项",
  "The logbook is empty. Open a flight and press “Log sighting”.": "日志为空。打开一个航班并点击“记录观测”。",
  "NEW AIRCRAFT": "新飞机",
  "NEW TYPE": "新机型",
  "✓ Logged": "✓ 已记录",
  "📓 Log sighting": "📓 记录观测",
  "Vert. speed": "垂直速度",
  "SkyTrack keeps running in the tray when you close the window": "关闭窗口后，SkyTrack 会继续在托盘中运行",
  "📓 Flight diary": "📓 飞行日记",
  "Keep running in the tray": "在托盘中继续运行",
  "Desktop notifications": "桌面通知",
  "In-app notifications": "应用内通知",
  "Flight diary": "飞行日记",
  "Flights": "航班",
  "Distance": "距离",
  "Around the Earth": "环绕地球",
  "(est.)": "（估算）",
  "From": "从",
  "To": "到",
  "Flight no.": "航班号",
  "Add": "添加",
  "Your diary is empty. Add a flight above, or open a flight on the map and press “Add to diary”.": "你的日记是空的。请在上方添加航班，或在地图上打开航班并点击“添加到日记”。",
  "Unknown airport: use an IATA or ICAO code, e.g. IST or LTFM": "未知机场：请使用 IATA 或 ICAO 代码，例如 IST 或 LTFM",
  "Share image": "分享图片",
  "Add to diary": "添加到日记",
  "Added to your diary": "已添加到你的日记",
  "Free flight tracker · no account, no ads": "免费航班追踪器 · 无需账号，无广告",
  "Image saved and copied to the clipboard": "图片已保存并复制到剪贴板",
  "Image saved": "图片已保存",
  "Altitude & speed": "高度和速度",
  "Landing": "降落",
  "Approaching": "进近",
  "Departed": "已起飞",
  "En route": "航行中",
  "A free flight tracker: no account, no ads. Here is a quick tour of what you can do.": "一款免费的航班追踪器：无需账号，无广告。下面快速了解你能做什么。",
  "Aircraft within {0} of your spot": "你所在位置 {0} 范围内的飞机",
  "Airline code": "航空公司代码",
  "Airport code": "机场代码",
  "Alert zone set ({0})": "警戒区已设置（{0}）",
  "Alerts": "提醒",
  "App": "应用",
  "Back": "返回",
  "Callsign contains": "呼号包含",
  "Choose where you are": "选择你的位置",
  "Click a plane to see its route, photo, altitude, speed and more. Click an airport (yellow dot) for its weather and arrivals.": "点击飞机可查看航路、照片、高度、速度等信息。点击机场（黄色圆点）可查看天气和到离港航班。",
  "Click any aircraft": "点击任意飞机",
  "Click the map to set your spot": "点击地图设置你的位置",
  "Click the map where you are, or type an airport code. SkyTrack lists the aircraft flying around that spot, with the direction to look and how high in the sky.": "在地图上点击你所在的位置，或输入机场代码。SkyTrack 会列出在该位置周围飞行的飞机，以及观察方向和天空中的高度。",
  "Click the map": "点击地图",
  "Move my spot": "移动我的位置",
  "Done": "完成",
  "Next": "下一步",
  "Download": "下载",
  "Downloading update {0}…": "正在下载更新 {0}…",
  "Get a notification when an aircraft you care about shows up on the map.": "当你关注的飞机出现在地图上时收到通知。",
  "Headwind {0}": "逆风 {0}",
  "Tailwind {0}": "顺风 {0}",
  "Helicopters": "直升机",
  "Hide or show the menu any time. Enjoy the sky!": "你可以随时隐藏或显示菜单。尽情享受天空吧！",
  "High turbulence risk ahead (~{0})": "前方有高强度颠簸风险（约 {0}）",
  "Moderate turbulence possible ahead (~{0})": "前方可能有中等颠簸（约 {0}）",
  "Keep a flight diary, set alerts for rare aircraft, see what is flying overhead, and change units in Settings.": "记录飞行日记、为稀有飞机设置提醒、查看头顶飞过的飞机，还可以在设置中更改单位。",
  "Menu button": "菜单按钮",
  "Military aircraft": "军用飞机",
  "Narrow the map by altitude, speed, airport, airline or aircraft type.": "按高度、速度、机场、航空公司或机型缩小地图范围。",
  "New version {0} available": "新版本 {0} 可用",
  "No alerts yet. Add one above.": "还没有提醒。请在上方添加。",
  "Nothing overhead right now.": "目前头顶没有飞机。",
  "Overhead": "头顶",
  "Radius": "半径",
  "Restart": "重启",
  "Search the whole world": "搜索全世界",
  "Settings": "设置",
  "Show the tour again": "再次显示引导",
  "Skip": "跳过",
  "Switch the whole app between English, Turkish, Spanish, German and French.": "在英语、土耳其语、西班牙语、德语、法语、阿拉伯语、中文、日语和韩语之间切换整个应用。",
  "Temperature": "温度",
  "Time": "时间",
  "Type a callsign, registration, aircraft type or airport. Results are not limited to the part of the map you see.": "输入呼号、注册号、机型或机场。结果不限于你看到的那部分地图。",
  "Units": "单位",
  "Update {0} is ready": "更新 {0} 已就绪",
  "Welcome to SkyTrack": "欢迎使用 SkyTrack",
  "Worldwide": "全球",
  "Your language": "你的语言",
  "Your tools": "你的工具",
  "e.g. A388, THY, TC-JNA": "例如 A388、THY、TC-JNA",
  "{0} flown · {1} to go": "已飞 {0} · 还剩 {1}",
  "{0} more aircraft match your alerts": "另有 {0} 架飞机符合你的提醒",
  "⚙ Settings": "⚙ 设置",
  "📍 Overhead": "📍 头顶",
  "🔔 Alerts": "🔔 提醒",
  "A free OpenSky API client gives the wide view a much higher daily limit. Create one in your OpenSky account. It is stored encrypted on this computer.": "免费的 OpenSky API 客户端可让广域视图获得高得多的每日额度。请在你的 OpenSky 账号中创建一个。它会加密存储在这台电脑上。",
  "Aircraft trails": "飞机轨迹",
  "Based on the aircraft SkyTrack has loaded around the map.": "基于 SkyTrack 在地图周围已加载的飞机。",
  "Busiest airports": "最繁忙的机场",
  "Clouds": "云",
  "Connected as {0}": "已连接为 {0}",
  "Could not store the credentials": "无法保存凭据",
  "Data sources are busy, retrying shortly. Showing the last known positions.": "数据源繁忙，稍后重试。正在显示最后已知位置。",
  "Fastest": "最快",
  "Highest": "最高",
  "How far back you can rewind": "可回溯多久",
  "In the air": "空中",
  "No connection to the data sources. Showing the last known positions.": "无法连接到数据源。正在显示最后已知位置。",
  "On the ground": "地面",
  "OpenSky account (optional)": "OpenSky 账号（可选）",
  "Replay history": "回放历史",
  "Satellite imagery with clouds (NASA, latest daily image)": "带云层的卫星图像（NASA，每日最新图像）",
  "Save": "保存",
  "Stats": "统计",
  "Top aircraft types": "热门机型",
  "Top airlines": "热门航空公司",
  "Trails": "轨迹",
  "You can also try Demo mode.": "你也可以试试演示模式。",
  "{0} aircraft with an emergency code": "{0} 架飞机发出紧急代码",
  "📊 Stats": "📊 统计",
  "OpenSky account saved": "OpenSky 账号已保存",
  "1) Sign up at opensky-network.org (free)  2) Account page → create an API client  3) Paste Client ID and secret here.": "1) 在 opensky-network.org 免费注册  2) 在账号页面创建 API 客户端  3) 在此粘贴 Client ID 和密钥。",
  "Open OpenSky account page": "打开 OpenSky 账号页面",
  "Tip: add a free OpenSky account in Settings to fill the wide view": "提示：在设置中添加免费的 OpenSky 账号可填满广域视图",
  "OpenSky account removed": "OpenSky 账号已移除",
  "Check for updates": "检查更新",
  "Checking…": "正在检查…",
  "You are up to date.": "已是最新版本。",
  "Version {0} found, downloading…": "发现版本 {0}，正在下载…",
  "Could not check for updates: {0}": "无法检查更新：{0}",
  "Version {0} is available: use the bar at the bottom of the menu.": "版本 {0} 可用：请使用菜单底部的横条。",
  "Thin ADS-B coverage here: some aircraft may be missing": "此处 ADS-B 覆盖稀疏：部分飞机可能缺失",
  "Seat tip": "座位小贴士",
  "Sun side": "阳光一侧",
  "Over the wings you feel turbulence least, the back rows most.": "坐在机翼上方颠簸感最轻，后排最明显。",
  "Right side": "右侧",
  "Left side": "左侧",
  "Route check": "航路检查",
  "🧭 Route check": "🧭 航路检查",
  "Is there turbulence on a route? Pick two airports to see what is reported along the way at three cruise altitudes.": "某条航路上有颠簸吗？选择两个机场，查看沿途三个巡航高度上的报告。",
  "Check route": "检查航路",
  "Use selected flight": "使用所选航班",
  "High turbulence risk": "高强度颠簸风险",
  "Moderate turbulence possible": "可能有中等颠簸",
  "Nothing reported": "无报告",
  "first about {0} from {1}": "距 {1} 约 {0} 后首次出现",
  "Based on SIGMET / G-AIRMET advisories and pilot reports from the last 2 hours. Nothing reported is not a guarantee.": "基于 SIGMET / G-AIRMET 警报和过去 2 小时内的飞行员报告。无报告并不代表保证安全。",
  "Show on map": "在地图上显示",
  "{0}: high turbulence risk ahead (~{1}). Keep your seat belt fastened.": "{0}：前方有高强度颠簸风险（约 {1}）。请系好安全带。",
  "{0}: moderate turbulence possible ahead (~{1}). Keep your seat belt fastened.": "{0}：前方可能有中等颠簸（约 {1}）。请系好安全带。",
  "{0}: nothing reported on the route ahead any more": "{0}：前方航路已不再有报告",
  "Enter a flight number, e.g. TK1 or THY1": "请输入航班号，例如 TK1 或 THY1",
  "Watching {0}: SkyTrack tells you when it is in the air, and about turbulence ahead": "正在关注 {0}：起飞时以及前方有颠簸时 SkyTrack 会通知你",
  "{0} is in the air: watching": "{0} 已升空：正在关注",
  "Watch a flight": "关注航班",
  "Enter a flight number. You get a notification when it is in the air and when there is turbulence ahead.": "输入航班号。该航班升空时以及前方有颠簸时你会收到通知。",
  "Flight number, e.g. TK1": "航班号，例如 TK1",
  "Watch": "关注",
  "waiting for departure": "等待起飞",
  "Copy tracking link": "复制追踪链接",
  "Tracking link copied": "追踪链接已复制",
  "Showing {0} of {1} aircraft · zoom in for all": "显示 {1} 架飞机中的 {0} 架 · 放大查看全部",
  "Thin out crowded areas when zoomed out": "缩小时合并拥挤区域",
  "Wide view: filling in, zoom in for all": "广域视图：正在填充，放大查看全部",
  "landed {0} ago": "{0}前降落",
  "just landed": "刚刚降落",
  "✕ Remove overhead spot": "✕ 移除“头顶”位置",
  "Remove my spot": "移除我的位置",
  "Your spot": "你的位置",
  "Overhead spot removed": "“头顶”位置已移除",
  "Click to switch between the animation and the dashed line": "点击可在动画和虚线之间切换",
  "Download and install": "下载并安装",
  "Install": "安装",
  "Update {0} downloaded": "更新 {0} 已下载",
  "Update download failed": "更新下载失败",
  "Open the download page": "打开下载页面",
  "The disk image was opened: drag SkyTrack to Applications": "磁盘映像已打开：请将 SkyTrack 拖到“应用程序”",
  "The AppImage is in your Downloads folder: make it executable and run it": "AppImage 在你的“下载”文件夹中：请将其设为可执行并运行"
};

DICT.ja = {
  "Close menu": "メニューを閉じる",
  "Open menu": "メニューを開く",
  "Mode": "モード",
  "Normal": "通常",
  "Plane spotter": "プレーンスポッター",
  "Data": "データ",
  "Demo": "デモ",
  "Live": "ライブ",
  "Map": "マップ",
  "Airports": "空港",
  "Alert zone": "警戒エリア",
  "Radar": "レーダー",
  "Rain radar": "雨レーダー",
  "Zone radius": "エリア半径",
  "High turbulence risk ahead (~{0} km)": "前方に強い乱気流の恐れ（約 {0} km）",
  "Moderate turbulence possible ahead (~{0} km)": "前方で中程度の乱気流の可能性（約 {0} km）",
  "No turbulence reported or forecast on the route ahead": "前方の航路で乱気流の報告や予報はありません",
  "Turbulence info unavailable": "乱気流情報を取得できません",
  "Checking route ahead…": "前方の航路を確認中…",
  "Wind": "風",
  "Headwind {0} kt": "向かい風 {0} kt",
  "Tailwind {0} kt": "追い風 {0} kt",
  "No significant head/tailwind": "顕著な向かい風・追い風なし",
  "~{0}% of tank left (est., incl. reserve)": "燃料残量 約{0}%（推定、予備含む）",
  "Fuel to go (est.)": "残り燃料（推定）",
  "arrives {0}": "{0} 到着予定",
  "Turbulence": "乱気流",
  "Turbulence advisories (SIGMET / G-AIRMET)": "乱気流情報（SIGMET / G-AIRMET）",
  "Wind arrows": "風向矢印",
  "Wind: FL050": "風: FL050",
  "Wind: FL100": "風: FL100",
  "Wind: FL180": "風: FL180",
  "Wind: FL300": "風: FL300",
  "Wind: FL340": "風: FL340",
  "Wind: FL390": "風: FL390",
  "Night": "夜",
  "Day / night": "昼夜",
  "Wind at {0}": "{0} の風",
  "Wind data unavailable": "風データを取得できません",
  "Turbulence data unavailable": "乱気流データを取得できません",
  "Moderate turbulence": "中程度の乱気流",
  "Severe turbulence": "強い乱気流",
  "No turbulence advisories right now": "現在、乱気流情報はありません",
  "Aircraft": "航空機",
  "{0} s ago": "{0} 秒前",
  "{0} min ago": "{0} 分前",
  "Standard": "標準",
  "Light": "ライト",
  "Dark": "ダーク",
  "Filters": "フィルター",
  "Altitude": "高度",
  "Min speed": "最低速度",
  "Airport": "空港",
  "Departure": "出発",
  "Arrival": "到着",
  "Departure ↔ arrival": "出発 ↔ 到着",
  "Airline": "航空会社",
  "e.g. THY, Pegasus, Lufthansa": "例: THY、Pegasus、Lufthansa",
  "Aircraft type": "機種",
  "e.g. B738, A320, boeing 777": "例: B738、A320、boeing 777",
  "Show aircraft on the ground": "地上の航空機を表示",
  "Favorites only ★": "お気に入りのみ ★",
  "Search callsign or registration…": "コールサインまたは登録記号を検索…",
  "● Live": "● ライブ",
  "history": "履歴",
  "min": "最小",
  "max": "最大",
  " min": " 分",
  " h ": " 時間 ",
  "on ground": "地上",
  "landed": "着陸済み",
  "Close": "閉じる",
  "Open photo": "写真を開く",
  "Previous photo": "前の写真",
  "Next photo": "次の写真",
  "Photo": "写真",
  "{0} entered the alert zone": "{0} が警戒エリアに入りました",
  "loading…": "読み込み中…",
  "error": "エラー",
  "last updated": "最終更新",
  "wide view: center only, zoom in": "広域表示: 中心部のみ、ズームインしてください",
  "demo (30x speed)": "デモ（30倍速）",
  "FLIGHTS": "フライト",
  "loading route info · {0} / {1} aircraft": "経路情報を読み込み中 · {0} / {1} 機",
  "Click the map to set the zone center": "マップをクリックしてエリアの中心を設定",
  "Alert zone set ({0} km)": "警戒エリアを設定しました（{0} km）",
  "{0} km flown · {1} km to go": "{0} km 飛行 · 残り {1} km",
  "Registration": "登録記号",
  "Speed": "速度",
  "Heading": "方位",
  "Vertical speed": "垂直速度",
  "Nearest airport": "最寄りの空港",
  "Position": "位置",
  "Owner": "所有者",
  "★ Favorited": "★ お気に入り済み",
  "☆ Favorite": "☆ お気に入り",
  "Loading route info…": "経路情報を読み込み中…",
  "Route info not found": "経路情報が見つかりません",
  "Couldn't load route info": "経路情報を読み込めませんでした",
  "ICAO24": "ICAO24",
  "Squawk": "スクォーク",
  "Category": "カテゴリ",
  "Country": "国",
  "Couldn't load airport info": "空港情報を読み込めませんでした",
  "Loading…": "読み込み中…",
  "Open on Wikipedia": "Wikipedia で開く",
  "Feels like": "体感温度",
  "Gusts": "突風",
  "Humidity": "湿度",
  "Pressure": "気圧",
  "Visibility": "視程",
  "Arrivals": "到着便",
  "Departures": "出発便",
  "Weather unavailable": "天気を取得できません",
  "Loading weather…": "天気を読み込み中…",
  "No aircraft loaded yet": "まだ航空機が読み込まれていません",
  "No arrivals found nearby": "近くに到着便がありません",
  "No departures found nearby": "近くに出発便がありません",
  "Clear sky": "快晴",
  "Mostly clear": "おおむね晴れ",
  "Partly cloudy": "晴れ時々曇り",
  "Overcast": "曇り",
  "Fog": "霧",
  "Freezing fog": "着氷性の霧",
  "Light drizzle": "弱い霧雨",
  "Drizzle": "霧雨",
  "Heavy drizzle": "強い霧雨",
  "Freezing drizzle": "着氷性の霧雨",
  "Light rain": "弱い雨",
  "Rain": "雨",
  "Heavy rain": "強い雨",
  "Freezing rain": "着氷性の雨",
  "Light snow": "弱い雪",
  "Snow": "雪",
  "Heavy snow": "大雪",
  "Snow grains": "雪あられ",
  "Rain showers": "にわか雨",
  "Violent showers": "激しいにわか雨",
  "Snow showers": "にわか雪",
  "Thunderstorm": "雷雨",
  "Thunderstorm, hail": "雹を伴う雷雨",
  "Hijacking": "ハイジャック",
  "Radio failure": "無線故障",
  "General emergency": "一般緊急事態",
  "Emergency": "緊急事態",
  "What does this code mean?": "このコードの意味は？",
  "{0} landed": "{0} が着陸しました",
  "{0} took off": "{0} が離陸しました",
  "Watching {0}: you will be notified when it takes off or lands": "{0} を監視中: 離陸・着陸時に通知します",
  "Watchlist": "ウォッチリスト",
  "last seen {0} min ago": "{0} 分前に最後に確認",
  "not seen yet": "まだ確認されていません",
  "Remove": "削除",
  "Not on the map right now": "現在マップ上にありません",
  "🔔 Watching": "🔔 監視中",
  "🔔 Watch": "🔔 監視",
  "Today's flights": "今日のフライト",
  "Couldn't load today's flights": "今日のフライトを読み込めませんでした",
  "No flights recorded today": "今日の記録はありません",
  "in flight": "飛行中",
  "now": "現在",
  "Radar unavailable": "レーダーを利用できません",
  "Already logged": "記録済み",
  "new aircraft": "新しい機体",
  "new type": "新しい機種",
  "Logged {0}": "{0} を記録しました",
  "Logbook": "観察ログ",
  "aircraft": "機体",
  "types": "機種",
  "airlines": "航空会社",
  "Open logbook": "ログを開く",
  "Export CSV": "CSV を書き出す",
  "The logbook is empty": "ログは空です",
  "Search the logbook…": "ログを検索…",
  "Nothing matches": "一致するものがありません",
  "The logbook is empty. Open a flight and press “Log sighting”.": "ログは空です。フライトを開いて「目撃を記録」を押してください。",
  "NEW AIRCRAFT": "新しい機体",
  "NEW TYPE": "新しい機種",
  "✓ Logged": "✓ 記録済み",
  "📓 Log sighting": "📓 目撃を記録",
  "Vert. speed": "垂直速度",
  "SkyTrack keeps running in the tray when you close the window": "ウィンドウを閉じても SkyTrack はトレイで動き続けます",
  "📓 Flight diary": "📓 フライト日記",
  "Keep running in the tray": "トレイで動かし続ける",
  "Desktop notifications": "デスクトップ通知",
  "In-app notifications": "アプリ内通知",
  "Flight diary": "フライト日記",
  "Flights": "フライト",
  "Distance": "距離",
  "Around the Earth": "地球一周",
  "(est.)": "（推定）",
  "From": "出発",
  "To": "到着",
  "Flight no.": "便名",
  "Add": "追加",
  "Your diary is empty. Add a flight above, or open a flight on the map and press “Add to diary”.": "日記は空です。上でフライトを追加するか、マップでフライトを開いて「日記に追加」を押してください。",
  "Unknown airport: use an IATA or ICAO code, e.g. IST or LTFM": "不明な空港: IATA または ICAO コードを使ってください（例: IST、LTFM）",
  "Share image": "画像を共有",
  "Add to diary": "日記に追加",
  "Added to your diary": "日記に追加しました",
  "Free flight tracker · no account, no ads": "無料のフライトトラッカー · アカウント不要、広告なし",
  "Image saved and copied to the clipboard": "画像を保存し、クリップボードにコピーしました",
  "Image saved": "画像を保存しました",
  "Altitude & speed": "高度と速度",
  "Landing": "着陸",
  "Approaching": "進入中",
  "Departed": "出発済み",
  "En route": "飛行中",
  "A free flight tracker: no account, no ads. Here is a quick tour of what you can do.": "無料のフライトトラッカー: アカウント不要、広告なし。できることをざっと紹介します。",
  "Aircraft within {0} of your spot": "現在地から {0} 以内の航空機",
  "Airline code": "航空会社コード",
  "Airport code": "空港コード",
  "Alert zone set ({0})": "警戒エリアを設定しました（{0}）",
  "Alerts": "アラート",
  "App": "アプリ",
  "Back": "戻る",
  "Callsign contains": "コールサインに含まれる文字",
  "Choose where you are": "現在地を選択",
  "Click a plane to see its route, photo, altitude, speed and more. Click an airport (yellow dot) for its weather and arrivals.": "飛行機をクリックすると、経路、写真、高度、速度などが見られます。空港（黄色い点）をクリックすると天気と発着便が表示されます。",
  "Click any aircraft": "飛行機をクリック",
  "Click the map to set your spot": "マップをクリックして現在地を設定",
  "Click the map where you are, or type an airport code. SkyTrack lists the aircraft flying around that spot, with the direction to look and how high in the sky.": "マップ上の現在地をクリックするか、空港コードを入力してください。SkyTrack がその周辺を飛ぶ航空機を、見る方向と空の高さとともに一覧表示します。",
  "Click the map": "マップをクリック",
  "Move my spot": "現在地を移動",
  "Done": "完了",
  "Next": "次へ",
  "Download": "ダウンロード",
  "Downloading update {0}…": "アップデート {0} をダウンロード中…",
  "Get a notification when an aircraft you care about shows up on the map.": "気になる航空機がマップに現れたら通知を受け取れます。",
  "Headwind {0}": "向かい風 {0}",
  "Tailwind {0}": "追い風 {0}",
  "Helicopters": "ヘリコプター",
  "Hide or show the menu any time. Enjoy the sky!": "メニューはいつでも隠したり表示したりできます。空をお楽しみください！",
  "High turbulence risk ahead (~{0})": "前方に強い乱気流の恐れ（約 {0}）",
  "Moderate turbulence possible ahead (~{0})": "前方で中程度の乱気流の可能性（約 {0}）",
  "Keep a flight diary, set alerts for rare aircraft, see what is flying overhead, and change units in Settings.": "フライト日記をつけたり、珍しい機体のアラートを設定したり、頭上を飛ぶ機体を確認したり、設定で単位を変更したりできます。",
  "Menu button": "メニューボタン",
  "Military aircraft": "軍用機",
  "Narrow the map by altitude, speed, airport, airline or aircraft type.": "高度、速度、空港、航空会社、機種でマップを絞り込みます。",
  "New version {0} available": "新バージョン {0} があります",
  "No alerts yet. Add one above.": "アラートはまだありません。上で追加してください。",
  "Nothing overhead right now.": "今は頭上に何もありません。",
  "Overhead": "頭上",
  "Radius": "半径",
  "Restart": "再起動",
  "Search the whole world": "世界中を検索",
  "Settings": "設定",
  "Show the tour again": "ツアーをもう一度表示",
  "Skip": "スキップ",
  "Switch the whole app between English, Turkish, Spanish, German and French.": "アプリ全体を英語、トルコ語、スペイン語、ドイツ語、フランス語、アラビア語、中国語、日本語、韓国語で切り替えます。",
  "Temperature": "温度",
  "Time": "時刻",
  "Type a callsign, registration, aircraft type or airport. Results are not limited to the part of the map you see.": "コールサイン、登録記号、機種、空港を入力してください。結果は表示中のマップ範囲に限りません。",
  "Units": "単位",
  "Update {0} is ready": "アップデート {0} の準備ができました",
  "Welcome to SkyTrack": "SkyTrack へようこそ",
  "Worldwide": "世界中",
  "Your language": "言語",
  "Your tools": "ツール",
  "e.g. A388, THY, TC-JNA": "例: A388、THY、TC-JNA",
  "{0} flown · {1} to go": "{0} 飛行 · 残り {1}",
  "{0} more aircraft match your alerts": "ほかに {0} 機がアラートに一致しています",
  "⚙ Settings": "⚙ 設定",
  "📍 Overhead": "📍 頭上",
  "🔔 Alerts": "🔔 アラート",
  "A free OpenSky API client gives the wide view a much higher daily limit. Create one in your OpenSky account. It is stored encrypted on this computer.": "無料の OpenSky API クライアントを使うと、広域表示の 1 日あたりの上限が大幅に上がります。OpenSky のアカウントで作成してください。このコンピューター上に暗号化して保存されます。",
  "Aircraft trails": "航跡",
  "Based on the aircraft SkyTrack has loaded around the map.": "SkyTrack がマップ周辺で読み込んだ航空機に基づきます。",
  "Busiest airports": "最も混雑する空港",
  "Clouds": "雲",
  "Connected as {0}": "{0} として接続済み",
  "Could not store the credentials": "認証情報を保存できませんでした",
  "Data sources are busy, retrying shortly. Showing the last known positions.": "データソースが混み合っています。まもなく再試行します。最後に確認した位置を表示しています。",
  "Fastest": "最速",
  "Highest": "最高",
  "How far back you can rewind": "さかのぼれる期間",
  "In the air": "飛行中",
  "No connection to the data sources. Showing the last known positions.": "データソースに接続できません。最後に確認した位置を表示しています。",
  "On the ground": "地上",
  "OpenSky account (optional)": "OpenSky アカウント（任意）",
  "Replay history": "履歴の再生",
  "Satellite imagery with clouds (NASA, latest daily image)": "雲付きの衛星画像（NASA、最新の日次画像）",
  "Save": "保存",
  "Stats": "統計",
  "Top aircraft types": "人気の機種",
  "Top airlines": "人気の航空会社",
  "Trails": "航跡",
  "You can also try Demo mode.": "デモモードもお試しいただけます。",
  "{0} aircraft with an emergency code": "緊急コードを発信中の航空機 {0} 機",
  "📊 Stats": "📊 統計",
  "OpenSky account saved": "OpenSky アカウントを保存しました",
  "1) Sign up at opensky-network.org (free)  2) Account page → create an API client  3) Paste Client ID and secret here.": "1) opensky-network.org に無料登録  2) アカウントページで API クライアントを作成  3) Client ID とシークレットをここに貼り付け。",
  "Open OpenSky account page": "OpenSky アカウントページを開く",
  "Tip: add a free OpenSky account in Settings to fill the wide view": "ヒント: 設定で無料の OpenSky アカウントを追加すると広域表示が埋まります",
  "OpenSky account removed": "OpenSky アカウントを削除しました",
  "Check for updates": "アップデートを確認",
  "Checking…": "確認中…",
  "You are up to date.": "最新の状態です。",
  "Version {0} found, downloading…": "バージョン {0} を検出、ダウンロード中…",
  "Could not check for updates: {0}": "アップデートを確認できませんでした: {0}",
  "Version {0} is available: use the bar at the bottom of the menu.": "バージョン {0} が利用可能です: メニュー下部のバーをご利用ください。",
  "Thin ADS-B coverage here: some aircraft may be missing": "この地域は ADS-B の受信網が薄く、一部の航空機が表示されないことがあります",
  "Seat tip": "座席のヒント",
  "Sun side": "太陽側",
  "Over the wings you feel turbulence least, the back rows most.": "翼の上あたりが乱気流を最も感じにくく、後方の座席が最も感じやすくなります。",
  "Right side": "右側",
  "Left side": "左側",
  "Route check": "航路チェック",
  "🧭 Route check": "🧭 航路チェック",
  "Is there turbulence on a route? Pick two airports to see what is reported along the way at three cruise altitudes.": "ある航路に乱気流はある？ 2 つの空港を選ぶと、途中の 3 つの巡航高度での報告を確認できます。",
  "Check route": "航路をチェック",
  "Use selected flight": "選択中のフライトを使用",
  "High turbulence risk": "強い乱気流の恐れ",
  "Moderate turbulence possible": "中程度の乱気流の可能性",
  "Nothing reported": "報告なし",
  "first about {0} from {1}": "{1} から約 {0} で最初に発生",
  "Based on SIGMET / G-AIRMET advisories and pilot reports from the last 2 hours. Nothing reported is not a guarantee.": "SIGMET / G-AIRMET と過去 2 時間のパイロット報告に基づきます。報告がないことは安全の保証ではありません。",
  "Show on map": "マップに表示",
  "{0}: high turbulence risk ahead (~{1}). Keep your seat belt fastened.": "{0}: 前方に強い乱気流の恐れ（約 {1}）。シートベルトをお締めください。",
  "{0}: moderate turbulence possible ahead (~{1}). Keep your seat belt fastened.": "{0}: 前方で中程度の乱気流の可能性（約 {1}）。シートベルトをお締めください。",
  "{0}: nothing reported on the route ahead any more": "{0}: 前方の航路の報告はなくなりました",
  "Enter a flight number, e.g. TK1 or THY1": "便名を入力してください（例: TK1 または THY1）",
  "Watching {0}: SkyTrack tells you when it is in the air, and about turbulence ahead": "{0} を監視中: 離陸時と前方の乱気流について SkyTrack がお知らせします",
  "{0} is in the air: watching": "{0} が飛行中: 監視しています",
  "Watch a flight": "フライトを監視",
  "Enter a flight number. You get a notification when it is in the air and when there is turbulence ahead.": "便名を入力してください。飛行中になったときと、前方に乱気流があるときに通知します。",
  "Flight number, e.g. TK1": "便名（例: TK1）",
  "Watch": "監視",
  "waiting for departure": "出発待ち",
  "Copy tracking link": "追跡リンクをコピー",
  "Tracking link copied": "追跡リンクをコピーしました",
  "Showing {0} of {1} aircraft · zoom in for all": "{1} 機中 {0} 機を表示中 · ズームインですべて表示",
  "Thin out crowded areas when zoomed out": "ズームアウト時に混雑エリアを間引く",
  "Wide view: filling in, zoom in for all": "広域表示: 補充中、ズームインですべて表示",
  "landed {0} ago": "{0}前に着陸",
  "just landed": "着陸したばかり",
  "✕ Remove overhead spot": "✕ 「頭上」の位置を削除",
  "Remove my spot": "現在地を削除",
  "Your spot": "現在地",
  "Overhead spot removed": "「頭上」の位置を削除しました",
  "Click to switch between the animation and the dashed line": "クリックでアニメーションと破線を切り替え",
  "Download and install": "ダウンロードしてインストール",
  "Install": "インストール",
  "Update {0} downloaded": "アップデート {0} をダウンロードしました",
  "Update download failed": "アップデートのダウンロードに失敗しました",
  "Open the download page": "ダウンロードページを開く",
  "The disk image was opened: drag SkyTrack to Applications": "ディスクイメージを開きました: SkyTrack を「アプリケーション」にドラッグしてください",
  "The AppImage is in your Downloads folder: make it executable and run it": "AppImage は「ダウンロード」フォルダにあります: 実行可能にして起動してください"
};

DICT.ko = {
  "Close menu": "메뉴 닫기",
  "Open menu": "메뉴 열기",
  "Mode": "모드",
  "Normal": "일반",
  "Plane spotter": "항공기 관측",
  "Data": "데이터",
  "Demo": "데모",
  "Live": "실시간",
  "Map": "지도",
  "Airports": "공항",
  "Alert zone": "경보 구역",
  "Radar": "레이더",
  "Rain radar": "강우 레이더",
  "Zone radius": "구역 반경",
  "High turbulence risk ahead (~{0} km)": "전방에 강한 난기류 위험 (약 {0} km)",
  "Moderate turbulence possible ahead (~{0} km)": "전방에 중간 난기류 가능성 (약 {0} km)",
  "No turbulence reported or forecast on the route ahead": "전방 항로에 난기류 보고나 예보가 없습니다",
  "Turbulence info unavailable": "난기류 정보를 사용할 수 없습니다",
  "Checking route ahead…": "전방 항로 확인 중…",
  "Wind": "바람",
  "Headwind {0} kt": "맞바람 {0} kt",
  "Tailwind {0} kt": "뒷바람 {0} kt",
  "No significant head/tailwind": "뚜렷한 맞바람/뒷바람 없음",
  "~{0}% of tank left (est., incl. reserve)": "연료 약 {0}% 남음 (추정, 예비 포함)",
  "Fuel to go (est.)": "남은 연료 (추정)",
  "arrives {0}": "{0} 도착",
  "Turbulence": "난기류",
  "Turbulence advisories (SIGMET / G-AIRMET)": "난기류 경보 (SIGMET / G-AIRMET)",
  "Wind arrows": "바람 화살표",
  "Wind: FL050": "바람: FL050",
  "Wind: FL100": "바람: FL100",
  "Wind: FL180": "바람: FL180",
  "Wind: FL300": "바람: FL300",
  "Wind: FL340": "바람: FL340",
  "Wind: FL390": "바람: FL390",
  "Night": "밤",
  "Day / night": "낮 / 밤",
  "Wind at {0}": "{0}의 바람",
  "Wind data unavailable": "바람 데이터를 사용할 수 없습니다",
  "Turbulence data unavailable": "난기류 데이터를 사용할 수 없습니다",
  "Moderate turbulence": "중간 난기류",
  "Severe turbulence": "강한 난기류",
  "No turbulence advisories right now": "현재 난기류 경보가 없습니다",
  "Aircraft": "항공기",
  "{0} s ago": "{0}초 전",
  "{0} min ago": "{0}분 전",
  "Standard": "표준",
  "Light": "밝게",
  "Dark": "어둡게",
  "Filters": "필터",
  "Altitude": "고도",
  "Min speed": "최소 속도",
  "Airport": "공항",
  "Departure": "출발",
  "Arrival": "도착",
  "Departure ↔ arrival": "출발 ↔ 도착",
  "Airline": "항공사",
  "e.g. THY, Pegasus, Lufthansa": "예: THY, Pegasus, Lufthansa",
  "Aircraft type": "기종",
  "e.g. B738, A320, boeing 777": "예: B738, A320, boeing 777",
  "Show aircraft on the ground": "지상의 항공기 표시",
  "Favorites only ★": "즐겨찾기만 ★",
  "Search callsign or registration…": "콜사인 또는 등록번호 검색…",
  "● Live": "● 실시간",
  "history": "기록",
  "min": "최소",
  "max": "최대",
  " min": " 분",
  " h ": " 시간 ",
  "on ground": "지상",
  "landed": "착륙함",
  "Close": "닫기",
  "Open photo": "사진 열기",
  "Previous photo": "이전 사진",
  "Next photo": "다음 사진",
  "Photo": "사진",
  "{0} entered the alert zone": "{0}이(가) 경보 구역에 진입했습니다",
  "loading…": "불러오는 중…",
  "error": "오류",
  "last updated": "마지막 업데이트",
  "wide view: center only, zoom in": "광역 보기: 중앙만 표시, 확대하세요",
  "demo (30x speed)": "데모 (30배속)",
  "FLIGHTS": "항공편",
  "loading route info · {0} / {1} aircraft": "경로 정보 불러오는 중 · {0} / {1}대",
  "Click the map to set the zone center": "지도를 클릭해 구역 중심을 설정하세요",
  "Alert zone set ({0} km)": "경보 구역이 설정되었습니다 ({0} km)",
  "{0} km flown · {1} km to go": "{0} km 비행 · {1} km 남음",
  "Registration": "등록번호",
  "Speed": "속도",
  "Heading": "방향",
  "Vertical speed": "수직 속도",
  "Nearest airport": "가장 가까운 공항",
  "Position": "위치",
  "Owner": "소유자",
  "★ Favorited": "★ 즐겨찾기됨",
  "☆ Favorite": "☆ 즐겨찾기",
  "Loading route info…": "경로 정보 불러오는 중…",
  "Route info not found": "경로 정보를 찾을 수 없습니다",
  "Couldn't load route info": "경로 정보를 불러오지 못했습니다",
  "ICAO24": "ICAO24",
  "Squawk": "스퀵",
  "Category": "분류",
  "Country": "국가",
  "Couldn't load airport info": "공항 정보를 불러오지 못했습니다",
  "Loading…": "불러오는 중…",
  "Open on Wikipedia": "위키백과에서 열기",
  "Feels like": "체감온도",
  "Gusts": "돌풍",
  "Humidity": "습도",
  "Pressure": "기압",
  "Visibility": "시정",
  "Arrivals": "도착편",
  "Departures": "출발편",
  "Weather unavailable": "날씨를 사용할 수 없습니다",
  "Loading weather…": "날씨 불러오는 중…",
  "No aircraft loaded yet": "아직 불러온 항공기가 없습니다",
  "No arrivals found nearby": "근처에 도착편이 없습니다",
  "No departures found nearby": "근처에 출발편이 없습니다",
  "Clear sky": "맑음",
  "Mostly clear": "대체로 맑음",
  "Partly cloudy": "구름 조금",
  "Overcast": "흐림",
  "Fog": "안개",
  "Freezing fog": "어는 안개",
  "Light drizzle": "약한 이슬비",
  "Drizzle": "이슬비",
  "Heavy drizzle": "강한 이슬비",
  "Freezing drizzle": "어는 이슬비",
  "Light rain": "약한 비",
  "Rain": "비",
  "Heavy rain": "강한 비",
  "Freezing rain": "어는 비",
  "Light snow": "약한 눈",
  "Snow": "눈",
  "Heavy snow": "폭설",
  "Snow grains": "싸락눈",
  "Rain showers": "소나기",
  "Violent showers": "강한 소나기",
  "Snow showers": "소낙눈",
  "Thunderstorm": "뇌우",
  "Thunderstorm, hail": "우박을 동반한 뇌우",
  "Hijacking": "하이재킹",
  "Radio failure": "무선 통신 장애",
  "General emergency": "일반 비상",
  "Emergency": "비상",
  "What does this code mean?": "이 코드는 무슨 뜻인가요?",
  "{0} landed": "{0} 착륙",
  "{0} took off": "{0} 이륙",
  "Watching {0}: you will be notified when it takes off or lands": "{0} 관찰 중: 이륙하거나 착륙하면 알려드립니다",
  "Watchlist": "관찰 목록",
  "last seen {0} min ago": "{0}분 전에 마지막으로 확인됨",
  "not seen yet": "아직 확인되지 않음",
  "Remove": "삭제",
  "Not on the map right now": "지금은 지도에 없습니다",
  "🔔 Watching": "🔔 관찰 중",
  "🔔 Watch": "🔔 관찰",
  "Today's flights": "오늘의 항공편",
  "Couldn't load today's flights": "오늘의 항공편을 불러오지 못했습니다",
  "No flights recorded today": "오늘 기록된 항공편이 없습니다",
  "in flight": "비행 중",
  "now": "지금",
  "Radar unavailable": "레이더를 사용할 수 없습니다",
  "Already logged": "이미 기록됨",
  "new aircraft": "새 항공기",
  "new type": "새 기종",
  "Logged {0}": "{0} 기록됨",
  "Logbook": "관측 기록",
  "aircraft": "항공기",
  "types": "기종",
  "airlines": "항공사",
  "Open logbook": "기록 열기",
  "Export CSV": "CSV 내보내기",
  "The logbook is empty": "기록이 비어 있습니다",
  "Search the logbook…": "기록 검색…",
  "Nothing matches": "일치하는 항목이 없습니다",
  "The logbook is empty. Open a flight and press “Log sighting”.": "기록이 비어 있습니다. 항공편을 열고 “관측 기록”을 누르세요.",
  "NEW AIRCRAFT": "새 항공기",
  "NEW TYPE": "새 기종",
  "✓ Logged": "✓ 기록됨",
  "📓 Log sighting": "📓 관측 기록",
  "Vert. speed": "수직 속도",
  "SkyTrack keeps running in the tray when you close the window": "창을 닫아도 SkyTrack은 트레이에서 계속 실행됩니다",
  "📓 Flight diary": "📓 비행 일기",
  "Keep running in the tray": "트레이에서 계속 실행",
  "Desktop notifications": "데스크톱 알림",
  "In-app notifications": "앱 내 알림",
  "Flight diary": "비행 일기",
  "Flights": "항공편",
  "Distance": "거리",
  "Around the Earth": "지구 한 바퀴",
  "(est.)": "(추정)",
  "From": "출발",
  "To": "도착",
  "Flight no.": "편명",
  "Add": "추가",
  "Your diary is empty. Add a flight above, or open a flight on the map and press “Add to diary”.": "일기가 비어 있습니다. 위에서 항공편을 추가하거나 지도에서 항공편을 열고 “일기에 추가”를 누르세요.",
  "Unknown airport: use an IATA or ICAO code, e.g. IST or LTFM": "알 수 없는 공항: IATA 또는 ICAO 코드를 사용하세요 (예: IST, LTFM)",
  "Share image": "이미지 공유",
  "Add to diary": "일기에 추가",
  "Added to your diary": "일기에 추가했습니다",
  "Free flight tracker · no account, no ads": "무료 항공편 추적기 · 계정 없음, 광고 없음",
  "Image saved and copied to the clipboard": "이미지를 저장하고 클립보드에 복사했습니다",
  "Image saved": "이미지를 저장했습니다",
  "Altitude & speed": "고도 및 속도",
  "Landing": "착륙",
  "Approaching": "접근 중",
  "Departed": "출발함",
  "En route": "비행 중",
  "A free flight tracker: no account, no ads. Here is a quick tour of what you can do.": "무료 항공편 추적기: 계정 없음, 광고 없음. 할 수 있는 일을 간단히 둘러보세요.",
  "Aircraft within {0} of your spot": "내 위치에서 {0} 이내의 항공기",
  "Airline code": "항공사 코드",
  "Airport code": "공항 코드",
  "Alert zone set ({0})": "경보 구역이 설정되었습니다 ({0})",
  "Alerts": "알림 설정",
  "App": "앱",
  "Back": "뒤로",
  "Callsign contains": "콜사인 포함 문자",
  "Choose where you are": "내 위치 선택",
  "Click a plane to see its route, photo, altitude, speed and more. Click an airport (yellow dot) for its weather and arrivals.": "비행기를 클릭하면 경로, 사진, 고도, 속도 등을 볼 수 있습니다. 공항(노란 점)을 클릭하면 날씨와 출도착편을 볼 수 있습니다.",
  "Click any aircraft": "비행기를 클릭하세요",
  "Click the map to set your spot": "지도를 클릭해 내 위치를 설정하세요",
  "Click the map where you are, or type an airport code. SkyTrack lists the aircraft flying around that spot, with the direction to look and how high in the sky.": "지도에서 내 위치를 클릭하거나 공항 코드를 입력하세요. SkyTrack이 그 주변을 비행하는 항공기를 바라볼 방향과 하늘에서의 높이와 함께 보여줍니다.",
  "Click the map": "지도를 클릭하세요",
  "Move my spot": "내 위치 이동",
  "Done": "완료",
  "Next": "다음",
  "Download": "다운로드",
  "Downloading update {0}…": "업데이트 {0} 다운로드 중…",
  "Get a notification when an aircraft you care about shows up on the map.": "관심 있는 항공기가 지도에 나타나면 알림을 받으세요.",
  "Headwind {0}": "맞바람 {0}",
  "Tailwind {0}": "뒷바람 {0}",
  "Helicopters": "헬리콥터",
  "Hide or show the menu any time. Enjoy the sky!": "메뉴는 언제든지 숨기거나 표시할 수 있습니다. 하늘을 즐기세요!",
  "High turbulence risk ahead (~{0})": "전방에 강한 난기류 위험 (약 {0})",
  "Moderate turbulence possible ahead (~{0})": "전방에 중간 난기류 가능성 (약 {0})",
  "Keep a flight diary, set alerts for rare aircraft, see what is flying overhead, and change units in Settings.": "비행 일기를 쓰고, 희귀 항공기 알림을 설정하고, 머리 위를 지나는 항공기를 확인하고, 설정에서 단위를 바꿔 보세요.",
  "Menu button": "메뉴 버튼",
  "Military aircraft": "군용기",
  "Narrow the map by altitude, speed, airport, airline or aircraft type.": "고도, 속도, 공항, 항공사 또는 기종으로 지도를 좁혀 보세요.",
  "New version {0} available": "새 버전 {0} 사용 가능",
  "No alerts yet. Add one above.": "아직 알림이 없습니다. 위에서 추가하세요.",
  "Nothing overhead right now.": "지금은 머리 위에 아무것도 없습니다.",
  "Overhead": "머리 위",
  "Radius": "반경",
  "Restart": "다시 시작",
  "Search the whole world": "전 세계 검색",
  "Settings": "설정",
  "Show the tour again": "둘러보기 다시 보기",
  "Skip": "건너뛰기",
  "Switch the whole app between English, Turkish, Spanish, German and French.": "앱 전체를 영어, 터키어, 스페인어, 독일어, 프랑스어, 아랍어, 중국어, 일본어, 한국어로 전환합니다.",
  "Temperature": "온도",
  "Time": "시간",
  "Type a callsign, registration, aircraft type or airport. Results are not limited to the part of the map you see.": "콜사인, 등록번호, 기종 또는 공항을 입력하세요. 결과는 보이는 지도 영역에 국한되지 않습니다.",
  "Units": "단위",
  "Update {0} is ready": "업데이트 {0} 준비됨",
  "Welcome to SkyTrack": "SkyTrack에 오신 것을 환영합니다",
  "Worldwide": "전 세계",
  "Your language": "언어",
  "Your tools": "도구",
  "e.g. A388, THY, TC-JNA": "예: A388, THY, TC-JNA",
  "{0} flown · {1} to go": "{0} 비행 · {1} 남음",
  "{0} more aircraft match your alerts": "알림과 일치하는 항공기가 {0}대 더 있습니다",
  "⚙ Settings": "⚙ 설정",
  "📍 Overhead": "📍 머리 위",
  "🔔 Alerts": "🔔 알림",
  "A free OpenSky API client gives the wide view a much higher daily limit. Create one in your OpenSky account. It is stored encrypted on this computer.": "무료 OpenSky API 클라이언트를 사용하면 광역 보기의 일일 한도가 크게 늘어납니다. OpenSky 계정에서 하나 만드세요. 이 컴퓨터에 암호화되어 저장됩니다.",
  "Aircraft trails": "항적",
  "Based on the aircraft SkyTrack has loaded around the map.": "SkyTrack이 지도 주변에서 불러온 항공기를 기준으로 합니다.",
  "Busiest airports": "가장 붐비는 공항",
  "Clouds": "구름",
  "Connected as {0}": "{0}(으)로 연결됨",
  "Could not store the credentials": "자격 증명을 저장하지 못했습니다",
  "Data sources are busy, retrying shortly. Showing the last known positions.": "데이터 소스가 혼잡합니다. 곧 다시 시도합니다. 마지막으로 알려진 위치를 표시합니다.",
  "Fastest": "가장 빠른",
  "Highest": "가장 높은",
  "How far back you can rewind": "얼마나 되감을 수 있는지",
  "In the air": "공중",
  "No connection to the data sources. Showing the last known positions.": "데이터 소스에 연결할 수 없습니다. 마지막으로 알려진 위치를 표시합니다.",
  "On the ground": "지상",
  "OpenSky account (optional)": "OpenSky 계정 (선택 사항)",
  "Replay history": "기록 재생",
  "Satellite imagery with clouds (NASA, latest daily image)": "구름이 있는 위성 영상 (NASA, 최신 일일 영상)",
  "Save": "저장",
  "Stats": "통계",
  "Top aircraft types": "인기 기종",
  "Top airlines": "인기 항공사",
  "Trails": "항적",
  "You can also try Demo mode.": "데모 모드도 사용해 보세요.",
  "{0} aircraft with an emergency code": "비상 코드를 보내는 항공기 {0}대",
  "📊 Stats": "📊 통계",
  "OpenSky account saved": "OpenSky 계정을 저장했습니다",
  "1) Sign up at opensky-network.org (free)  2) Account page → create an API client  3) Paste Client ID and secret here.": "1) opensky-network.org에 무료 가입  2) 계정 페이지에서 API 클라이언트 만들기  3) Client ID와 시크릿을 여기에 붙여넣기.",
  "Open OpenSky account page": "OpenSky 계정 페이지 열기",
  "Tip: add a free OpenSky account in Settings to fill the wide view": "팁: 설정에서 무료 OpenSky 계정을 추가하면 광역 보기가 채워집니다",
  "OpenSky account removed": "OpenSky 계정을 삭제했습니다",
  "Check for updates": "업데이트 확인",
  "Checking…": "확인 중…",
  "You are up to date.": "최신 버전입니다.",
  "Version {0} found, downloading…": "버전 {0}을(를) 찾았습니다. 다운로드 중…",
  "Could not check for updates: {0}": "업데이트를 확인하지 못했습니다: {0}",
  "Version {0} is available: use the bar at the bottom of the menu.": "버전 {0}을(를) 사용할 수 있습니다: 메뉴 하단의 막대를 사용하세요.",
  "Thin ADS-B coverage here: some aircraft may be missing": "이 지역은 ADS-B 수신망이 부족합니다: 일부 항공기가 보이지 않을 수 있습니다",
  "Seat tip": "좌석 팁",
  "Sun side": "햇빛 쪽",
  "Over the wings you feel turbulence least, the back rows most.": "날개 위쪽에서는 난기류를 가장 적게, 뒷좌석에서는 가장 많이 느낍니다.",
  "Right side": "오른쪽",
  "Left side": "왼쪽",
  "Route check": "경로 확인",
  "🧭 Route check": "🧭 경로 확인",
  "Is there turbulence on a route? Pick two airports to see what is reported along the way at three cruise altitudes.": "이 경로에 난기류가 있을까요? 공항 두 곳을 선택하면 세 가지 순항 고도에서 경로상 보고된 내용을 볼 수 있습니다.",
  "Check route": "경로 확인",
  "Use selected flight": "선택한 항공편 사용",
  "High turbulence risk": "강한 난기류 위험",
  "Moderate turbulence possible": "중간 난기류 가능성",
  "Nothing reported": "보고 없음",
  "first about {0} from {1}": "{1}에서 약 {0} 후 처음",
  "Based on SIGMET / G-AIRMET advisories and pilot reports from the last 2 hours. Nothing reported is not a guarantee.": "SIGMET / G-AIRMET 경보와 최근 2시간의 조종사 보고를 기반으로 합니다. 보고가 없다고 안전을 보장하지는 않습니다.",
  "Show on map": "지도에 표시",
  "{0}: high turbulence risk ahead (~{1}). Keep your seat belt fastened.": "{0}: 전방에 강한 난기류 위험 (약 {1}). 안전벨트를 착용하세요.",
  "{0}: moderate turbulence possible ahead (~{1}). Keep your seat belt fastened.": "{0}: 전방에 중간 난기류 가능성 (약 {1}). 안전벨트를 착용하세요.",
  "{0}: nothing reported on the route ahead any more": "{0}: 전방 항로에 더 이상 보고가 없습니다",
  "Enter a flight number, e.g. TK1 or THY1": "편명을 입력하세요 (예: TK1 또는 THY1)",
  "Watching {0}: SkyTrack tells you when it is in the air, and about turbulence ahead": "{0} 관찰 중: 이륙했을 때와 전방 난기류에 대해 SkyTrack이 알려드립니다",
  "{0} is in the air: watching": "{0}이(가) 비행 중: 관찰 중",
  "Watch a flight": "항공편 관찰",
  "Enter a flight number. You get a notification when it is in the air and when there is turbulence ahead.": "편명을 입력하세요. 비행 중일 때와 전방에 난기류가 있을 때 알림을 받습니다.",
  "Flight number, e.g. TK1": "편명, 예: TK1",
  "Watch": "관찰",
  "waiting for departure": "출발 대기 중",
  "Copy tracking link": "추적 링크 복사",
  "Tracking link copied": "추적 링크를 복사했습니다",
  "Showing {0} of {1} aircraft · zoom in for all": "{1}대 중 {0}대 표시 중 · 확대하면 모두 표시",
  "Thin out crowded areas when zoomed out": "축소 시 붐비는 지역 줄이기",
  "Wide view: filling in, zoom in for all": "광역 보기: 채우는 중, 확대하면 모두 표시",
  "landed {0} ago": "{0} 전에 착륙",
  "just landed": "방금 착륙",
  "✕ Remove overhead spot": "✕ “머리 위” 위치 삭제",
  "Remove my spot": "내 위치 삭제",
  "Your spot": "내 위치",
  "Overhead spot removed": "“머리 위” 위치를 삭제했습니다",
  "Click to switch between the animation and the dashed line": "클릭하여 애니메이션과 점선 간 전환",
  "Download and install": "다운로드 및 설치",
  "Install": "설치",
  "Update {0} downloaded": "업데이트 {0} 다운로드 완료",
  "Update download failed": "업데이트 다운로드 실패",
  "Open the download page": "다운로드 페이지 열기",
  "The disk image was opened: drag SkyTrack to Applications": "디스크 이미지가 열렸습니다: SkyTrack을 응용 프로그램으로 드래그하세요",
  "The AppImage is in your Downloads folder: make it executable and run it": "AppImage가 다운로드 폴더에 있습니다: 실행 가능하게 만든 후 실행하세요"
};
Object.assign(DICT.tr, {
  "Runways": "Pist",
  "longest {0}": "en uzun {0}"
});
Object.assign(DICT.es, {
  "Runways": "Pistas",
  "longest {0}": "más larga {0}"
});
Object.assign(DICT.de, {
  "Runways": "Landebahnen",
  "longest {0}": "längste {0}"
});
Object.assign(DICT.fr, {
  "Runways": "Pistes",
  "longest {0}": "la plus longue {0}"
});
Object.assign(DICT.ar, {
  "Runways": "المدارج",
  "longest {0}": "الأطول {0}"
});
Object.assign(DICT.zh, {
  "Runways": "跑道",
  "longest {0}": "最长 {0}"
});
Object.assign(DICT.ja, {
  "Runways": "滑走路",
  "longest {0}": "最長 {0}"
});
Object.assign(DICT.ko, {
  "Runways": "활주로",
  "longest {0}": "가장 긴 활주로 {0}"
});
