// Spanish, German and French UI texts (keys are the English texts, same as the Turkish table in i18n.js). Missing keys fall back to English.
DICT.es = {
  'Close menu': 'Cerrar menú', 'Open menu': 'Abrir menú', 'Mode': 'Modo', 'Normal': 'Normal', 'Plane spotter': 'Spotter de aviones', 'Data': 'Datos', 'Demo': 'Demo', 'Live': 'En vivo',
  'Map': 'Mapa', 'Airports': 'Aeropuertos', 'Alert zone': 'Zona de alerta', 'Radar': 'Radar', 'Rain radar': 'Radar de lluvia', 'Zone radius': 'Radio de la zona',
  'High turbulence risk ahead (~{0} km)': 'Riesgo alto de turbulencia por delante (~{0} km)', 'Moderate turbulence possible ahead (~{0} km)': 'Posible turbulencia moderada por delante (~{0} km)',
  'No turbulence reported or forecast on the route ahead': 'Sin turbulencias notificadas ni previstas en la ruta', 'Turbulence info unavailable': 'Información de turbulencia no disponible', 'Checking route ahead…': 'Comprobando la ruta…',
  'Wind': 'Viento', 'Headwind {0} kt': 'Viento de cara {0} kt', 'Tailwind {0} kt': 'Viento de cola {0} kt', 'No significant head/tailwind': 'Sin viento de cara/cola relevante', '~{0}% of tank left (est., incl. reserve)': '~{0}% del depósito restante (est., con reserva)', 'Fuel to go (est.)': 'Combustible restante (est.)', 'arrives {0}': 'llega {0}',
  'Turbulence': 'Turbulencia', 'Turbulence advisories (SIGMET / G-AIRMET)': 'Avisos de turbulencia (SIGMET / G-AIRMET)', 'Wind arrows': 'Flechas de viento', 'Wind: FL050': 'Viento: FL050', 'Wind: FL100': 'Viento: FL100', 'Wind: FL180': 'Viento: FL180', 'Wind: FL300': 'Viento: FL300', 'Wind: FL340': 'Viento: FL340', 'Wind: FL390': 'Viento: FL390', 'Night': 'Noche', 'Day / night': 'Día / noche',
  'Wind at {0}': 'Viento a {0}', 'Wind data unavailable': 'Datos de viento no disponibles', 'Turbulence data unavailable': 'Datos de turbulencia no disponibles', 'Moderate turbulence': 'Turbulencia moderada', 'Severe turbulence': 'Turbulencia severa', 'No turbulence advisories right now': 'Sin avisos de turbulencia ahora',
  'Aircraft': 'Aeronaves', '{0} s ago': 'hace {0} s', '{0} min ago': 'hace {0} min',
  'Standard': 'Estándar', 'Light': 'Claro', 'Dark': 'Oscuro', 'Filters': 'Filtros', 'Altitude': 'Altitud', 'Min speed': 'Velocidad mín.', 'Airport': 'Aeropuerto',
  'Departure': 'Salida', 'Arrival': 'Llegada', 'Departure ↔ arrival': 'Salida ↔ llegada', 'Airline': 'Aerolínea', 'e.g. THY, Pegasus, Lufthansa': 'p. ej. Iberia, Vueling, Lufthansa',
  'Aircraft type': 'Tipo de aeronave', 'e.g. B738, A320, boeing 777': 'p. ej. B738, A320, boeing 777', 'Show aircraft on the ground': 'Mostrar aeronaves en tierra',
  'Favorites only ★': 'Solo favoritos ★', 'Search callsign or registration…': 'Buscar indicativo o matrícula…',
  '● Live': '● En vivo', 'history': 'historial', 'min': 'mín', 'max': 'máx', ' min': ' min', ' h ': ' h ',
  'on ground': 'en tierra', 'landed': 'aterrizó', 'Close': 'Cerrar', 'Open photo': 'Abrir foto', 'Previous photo': 'Foto anterior', 'Next photo': 'Foto siguiente', 'Photo': 'Foto',
  '{0} entered the alert zone': '{0} entró en la zona de alerta', 'loading…': 'cargando…', 'error': 'error', 'last updated': 'última actualización',
  'wide view: center only, zoom in': 'vista amplia: solo el centro, acerca el mapa', 'demo (30x speed)': 'demo (velocidad ×30)', 'FLIGHTS': 'VUELOS',
  'loading route info · {0} / {1} aircraft': 'cargando rutas · {0} / {1} aeronaves', 'Click the map to set the zone center': 'Haz clic en el mapa para fijar el centro de la zona',
  'Alert zone set ({0} km)': 'Zona de alerta fijada ({0} km)', '{0} km flown · {1} km to go': '{0} km recorridos · {1} km restantes',
  'Registration': 'Matrícula', 'Speed': 'Velocidad', 'Heading': 'Rumbo', 'Vertical speed': 'Velocidad vertical', 'Nearest airport': 'Aeropuerto más cercano', 'Position': 'Posición', 'Owner': 'Propietario',
  '★ Favorited': '★ En favoritos', '☆ Favorite': '☆ Favorito', 'Loading route info…': 'Cargando ruta…', 'Route info not found': 'Ruta no encontrada',
  "Couldn't load route info": 'No se pudo cargar la ruta', 'ICAO24': 'ICAO24', 'Squawk': 'Squawk', 'Category': 'Categoría', 'Country': 'País',
  "Couldn't load airport info": 'No se pudo cargar la información del aeropuerto', 'Loading…': 'Cargando…', 'Open on Wikipedia': 'Abrir en Wikipedia', 'Feels like': 'Sensación', 'Gusts': 'Rachas',
  'Humidity': 'Humedad', 'Pressure': 'Presión', 'Visibility': 'Visibilidad', 'Arrivals': 'Llegadas', 'Departures': 'Salidas', 'Weather unavailable': 'Tiempo no disponible',
  'Loading weather…': 'Cargando el tiempo…', 'No aircraft loaded yet': 'Aún no hay aeronaves cargadas', 'No arrivals found nearby': 'No hay llegadas cerca', 'No departures found nearby': 'No hay salidas cerca',
  'Clear sky': 'Despejado', 'Mostly clear': 'Mayormente despejado', 'Partly cloudy': 'Parcialmente nublado', 'Overcast': 'Cubierto', 'Fog': 'Niebla', 'Freezing fog': 'Niebla helada', 'Light drizzle': 'Llovizna ligera',
  'Drizzle': 'Llovizna', 'Heavy drizzle': 'Llovizna intensa', 'Freezing drizzle': 'Llovizna helada', 'Light rain': 'Lluvia ligera', 'Rain': 'Lluvia', 'Heavy rain': 'Lluvia fuerte',
  'Freezing rain': 'Lluvia helada', 'Light snow': 'Nieve ligera', 'Snow': 'Nieve', 'Heavy snow': 'Nieve intensa', 'Snow grains': 'Granos de nieve', 'Rain showers': 'Chubascos', 'Violent showers': 'Chubascos fuertes',
  'Snow showers': 'Chubascos de nieve', 'Thunderstorm': 'Tormenta', 'Thunderstorm, hail': 'Tormenta con granizo',
  'Hijacking': 'Secuestro', 'Radio failure': 'Fallo de radio', 'General emergency': 'Emergencia general', 'Emergency': 'Emergencia', 'What does this code mean?': '¿Qué significa este código?',
  '{0} landed': '{0} ha aterrizado', '{0} took off': '{0} ha despegado', 'Watching {0}: you will be notified when it takes off or lands': 'Siguiendo {0}: recibirás un aviso al despegar o aterrizar',
  'Watchlist': 'Lista de seguimiento', 'last seen {0} min ago': 'visto hace {0} min', 'not seen yet': 'aún no visto', 'Remove': 'Quitar', 'Not on the map right now': 'No está en el mapa ahora',
  '🔔 Watching': '🔔 Siguiendo', '🔔 Watch': '🔔 Seguir', "Today's flights": 'Vuelos de hoy', "Couldn't load today's flights": 'No se pudieron cargar los vuelos de hoy',
  'No flights recorded today': 'Hoy no hay vuelos registrados', 'in flight': 'en vuelo', 'now': 'ahora', 'Radar unavailable': 'Radar no disponible',
  'Already logged': 'Ya registrado', 'new aircraft': 'aeronave nueva', 'new type': 'tipo nuevo', 'Logged {0}': '{0} registrado', 'Logbook': 'Cuaderno', 'aircraft': 'aeronaves', 'types': 'tipos',
  'airlines': 'aerolíneas', 'Open logbook': 'Abrir cuaderno', 'Export CSV': 'Exportar CSV', 'The logbook is empty': 'El cuaderno está vacío', 'Search the logbook…': 'Buscar en el cuaderno…',
  'Nothing matches': 'Sin coincidencias', 'The logbook is empty. Open a flight and press “Log sighting”.': 'El cuaderno está vacío. Abre un vuelo y pulsa «Registrar avistamiento».',
  'NEW AIRCRAFT': 'AERONAVE NUEVA', 'NEW TYPE': 'TIPO NUEVO', '✓ Logged': '✓ Registrado', '📓 Log sighting': '📓 Registrar avistamiento',
  'Vert. speed': 'Vel. vertical', 'SkyTrack keeps running in the tray when you close the window': 'SkyTrack sigue funcionando en la bandeja al cerrar la ventana', '📓 Flight diary': '📓 Diario de vuelos',
  'Keep running in the tray': 'Seguir en la bandeja del sistema', 'Desktop notifications': 'Notificaciones de escritorio', 'Flight diary': 'Diario de vuelos', 'Flights': 'Vuelos', 'Distance': 'Distancia', 'Around the Earth': 'Vueltas al mundo',
  '(est.)': '(est.)', 'From': 'Origen', 'To': 'Destino', 'Flight no.': 'N.º de vuelo', 'Add': 'Añadir',
  'Your diary is empty. Add a flight above, or open a flight on the map and press “Add to diary”.': 'Tu diario está vacío. Añade un vuelo arriba o abre uno en el mapa y pulsa «Añadir al diario».',
  'Unknown airport: use an IATA or ICAO code, e.g. IST or LTFM': 'Aeropuerto desconocido: usa un código IATA u OACI, p. ej. MAD o LEMD', 'Share image': 'Compartir imagen', 'Add to diary': 'Añadir al diario', 'Added to your diary': 'Añadido a tu diario',
  'Free flight tracker · no account, no ads': 'Seguimiento de vuelos gratis · sin cuenta ni anuncios', 'Image saved and copied to the clipboard': 'Imagen guardada y copiada al portapapeles', 'Image saved': 'Imagen guardada', 'Altitude & speed': 'Altitud y velocidad',
  'Landing': 'Aterrizando', 'Approaching': 'Aproximándose', 'Departed': 'Ha salido', 'En route': 'En ruta',
  'A free flight tracker: no account, no ads. Here is a quick tour of what you can do.': 'Un seguimiento de vuelos gratuito: sin cuenta ni anuncios. Un recorrido rápido por lo que puedes hacer.',
  'Aircraft within {0} of your spot': 'Aeronaves a menos de {0} de tu punto',
  'Airline code': 'Código de aerolínea',
  'Airport code': 'Código de aeropuerto',
  'Alert zone set ({0})': 'Zona de alerta fijada ({0})',
  'Alerts': 'Alertas',
  'App': 'Aplicación',
  'Back': 'Atrás',
  'Callsign contains': 'El indicativo contiene',
  'Choose where you are': 'Elige dónde estás',
  'Click a plane to see its route, photo, altitude, speed and more. Click an airport (yellow dot) for its weather and arrivals.': 'Haz clic en un avión para ver su ruta, foto, altitud, velocidad y más. Haz clic en un aeropuerto (punto amarillo) para ver el tiempo y las llegadas.',
  'Click any aircraft': 'Haz clic en cualquier avión',
  'Click the map to set your spot': 'Haz clic en el mapa para fijar tu punto',
  'Click the map where you are, or type an airport code. SkyTrack lists the aircraft flying around that spot, with the direction to look and how high in the sky.': 'Haz clic en el mapa donde estás o escribe un código de aeropuerto. SkyTrack lista las aeronaves que vuelan alrededor, con la dirección en que mirar y a qué altura en el cielo.',
  'Click the map': 'Haz clic en el mapa',
  'Move my spot': 'Mover mi punto',
  'Done': 'Listo',
  'Next': 'Siguiente',
  'Download': 'Descargar',
  'Downloading update {0}…': 'Descargando la actualización {0}…',
  'Get a notification when an aircraft you care about shows up on the map.': 'Recibe un aviso cuando aparezca en el mapa una aeronave que te interese.',
  'Headwind {0}': 'Viento de cara {0}',
  'Tailwind {0}': 'Viento de cola {0}',
  'Helicopters': 'Helicópteros',
  'Hide or show the menu any time. Enjoy the sky!': 'Oculta o muestra el menú cuando quieras. ¡Disfruta del cielo!',
  'High turbulence risk ahead (~{0})': 'Riesgo alto de turbulencia por delante (~{0})',
  'Moderate turbulence possible ahead (~{0})': 'Posible turbulencia moderada por delante (~{0})',
  'Keep a flight diary, set alerts for rare aircraft, see what is flying overhead, and change units in Settings.': 'Lleva un diario de vuelos, crea alertas de aeronaves poco comunes, mira qué vuela sobre ti y cambia las unidades en Ajustes.',
  'Menu button': 'Botón del menú',
  'Military aircraft': 'Aeronaves militares',
  'Narrow the map by altitude, speed, airport, airline or aircraft type.': 'Filtra el mapa por altitud, velocidad, aeropuerto, aerolínea o tipo de aeronave.',
  'New version {0} available': 'Nueva versión {0} disponible',
  'No alerts yet. Add one above.': 'Aún no hay alertas. Añade una arriba.',
  'Nothing overhead right now.': 'Ahora no hay nada sobre ti.',
  'Overhead': 'Sobre mí',
  'Radius': 'Radio',
  'Restart': 'Reiniciar',
  'Search the whole world': 'Busca en todo el mundo',
  'Settings': 'Ajustes',
  'Show the tour again': 'Mostrar el recorrido otra vez',
  'Skip': 'Omitir',
  'Switch the whole app between English, Turkish, Spanish, German and French.': 'Cambia toda la aplicación entre inglés, turco, español, alemán y francés.',
  'Temperature': 'Temperatura',
  'Time': 'Hora',
  'Type a callsign, registration, aircraft type or airport. Results are not limited to the part of the map you see.': 'Escribe un indicativo, matrícula, tipo de aeronave o aeropuerto. Los resultados no se limitan a la parte del mapa que ves.',
  'Units': 'Unidades',
  'Update {0} is ready': 'La actualización {0} está lista',
  'Welcome to SkyTrack': 'Bienvenido a SkyTrack',
  'Worldwide': 'En todo el mundo',
  'Your language': 'Tu idioma',
  'Your tools': 'Tus herramientas',
  'e.g. A388, THY, TC-JNA': 'p. ej. A388, IBE, EC-MXV',
  '{0} flown · {1} to go': '{0} recorridos · {1} restantes',
  '{0} more aircraft match your alerts': '{0} aeronaves más coinciden con tus alertas',
  '⚙ Settings': '⚙ Ajustes',
  '📍 Overhead': '📍 Sobre mí',
  '🔔 Alerts': '🔔 Alertas',
  'A free OpenSky API client gives the wide view a much higher daily limit. Create one in your OpenSky account. It is stored encrypted on this computer.': 'Un cliente de la API de OpenSky gratuito da a la vista amplia un límite diario mucho mayor. Crea uno en tu cuenta de OpenSky. Se guarda cifrado en este ordenador.',
  'Aircraft trails': 'Estelas de aeronaves',
  'Based on the aircraft SkyTrack has loaded around the map.': 'Basado en las aeronaves que SkyTrack ha cargado alrededor del mapa.',
  'Busiest airports': 'Aeropuertos más activos',
  'Clouds': 'Nubes',
  'Connected as {0}': 'Conectado como {0}',
  'Could not store the credentials': 'No se pudieron guardar las credenciales',
  'Data sources are busy, retrying shortly. Showing the last known positions.': 'Las fuentes de datos están saturadas, se reintentará en breve. Se muestran las últimas posiciones conocidas.',
  'Fastest': 'Más rápido',
  'Highest': 'Más alto',
  'How far back you can rewind': 'Hasta dónde puedes rebobinar',
  'In the air': 'En el aire',
  'No connection to the data sources. Showing the last known positions.': 'Sin conexión con las fuentes de datos. Se muestran las últimas posiciones conocidas.',
  'On the ground': 'En tierra',
  'OpenSky account (optional)': 'Cuenta de OpenSky (opcional)',
  'Replay history': 'Historial de repetición',
  'Satellite imagery with clouds (NASA, latest daily image)': 'Imagen de satélite con nubes (NASA, última imagen diaria)',
  'Save': 'Guardar',
  'Stats': 'Estadísticas',
  'Top aircraft types': 'Tipos más frecuentes',
  'Top airlines': 'Aerolíneas más frecuentes',
  'Trails': 'Estelas',
  'You can also try Demo mode.': 'También puedes probar el modo demo.',
  '{0} aircraft with an emergency code': '{0} aeronaves con código de emergencia',
  '📊 Stats': '📊 Estadísticas',
  'OpenSky account saved': 'Cuenta de OpenSky guardada',
  'OpenSky account removed': 'Cuenta de OpenSky eliminada',
  'Check for updates': 'Buscar actualizaciones',
  'Checking…': 'Comprobando…',
  'You are up to date.': 'Estás al día.',
  'Version {0} found, downloading…': 'Versión {0} encontrada, descargando…',
  'Could not check for updates: {0}': 'No se pudo buscar actualizaciones: {0}',
  'Version {0} is available: use the bar at the bottom of the menu.': 'La versión {0} está disponible: usa la barra de la parte inferior del menú.'
};
DICT.de = {
  'Close menu': 'Menü schließen', 'Open menu': 'Menü öffnen', 'Mode': 'Modus', 'Normal': 'Normal', 'Plane spotter': 'Planespotter', 'Data': 'Daten', 'Demo': 'Demo', 'Live': 'Live',
  'Map': 'Karte', 'Airports': 'Flughäfen', 'Alert zone': 'Alarmzone', 'Radar': 'Radar', 'Rain radar': 'Regenradar', 'Zone radius': 'Zonenradius',
  'High turbulence risk ahead (~{0} km)': 'Hohes Turbulenzrisiko voraus (~{0} km)', 'Moderate turbulence possible ahead (~{0} km)': 'Mäßige Turbulenzen voraus möglich (~{0} km)',
  'No turbulence reported or forecast on the route ahead': 'Keine Turbulenzen gemeldet oder vorhergesagt', 'Turbulence info unavailable': 'Turbulenzdaten nicht verfügbar', 'Checking route ahead…': 'Strecke voraus wird geprüft…',
  'Wind': 'Wind', 'Headwind {0} kt': 'Gegenwind {0} kt', 'Tailwind {0} kt': 'Rückenwind {0} kt', 'No significant head/tailwind': 'Kein nennenswerter Gegen-/Rückenwind', '~{0}% of tank left (est., incl. reserve)': '~{0} % Resttank (geschätzt, inkl. Reserve)', 'Fuel to go (est.)': 'Restkraftstoff (geschätzt)', 'arrives {0}': 'Ankunft {0}',
  'Turbulence': 'Turbulenz', 'Turbulence advisories (SIGMET / G-AIRMET)': 'Turbulenzwarnungen (SIGMET / G-AIRMET)', 'Wind arrows': 'Windpfeile', 'Wind: FL050': 'Wind: FL050', 'Wind: FL100': 'Wind: FL100', 'Wind: FL180': 'Wind: FL180', 'Wind: FL300': 'Wind: FL300', 'Wind: FL340': 'Wind: FL340', 'Wind: FL390': 'Wind: FL390', 'Night': 'Nacht', 'Day / night': 'Tag / Nacht',
  'Wind at {0}': 'Wind auf {0}', 'Wind data unavailable': 'Winddaten nicht verfügbar', 'Turbulence data unavailable': 'Turbulenzdaten nicht verfügbar', 'Moderate turbulence': 'Mäßige Turbulenz', 'Severe turbulence': 'Starke Turbulenz', 'No turbulence advisories right now': 'Derzeit keine Turbulenzwarnungen',
  'Aircraft': 'Flugzeuge', '{0} s ago': 'vor {0} s', '{0} min ago': 'vor {0} Min.',
  'Standard': 'Standard', 'Light': 'Hell', 'Dark': 'Dunkel', 'Filters': 'Filter', 'Altitude': 'Flughöhe', 'Min speed': 'Mindestgeschw.', 'Airport': 'Flughafen',
  'Departure': 'Abflug', 'Arrival': 'Ankunft', 'Departure ↔ arrival': 'Abflug ↔ Ankunft', 'Airline': 'Fluggesellschaft', 'e.g. THY, Pegasus, Lufthansa': 'z. B. Lufthansa, Eurowings, Condor',
  'Aircraft type': 'Flugzeugtyp', 'e.g. B738, A320, boeing 777': 'z. B. B738, A320, Boeing 777', 'Show aircraft on the ground': 'Flugzeuge am Boden anzeigen',
  'Favorites only ★': 'Nur Favoriten ★', 'Search callsign or registration…': 'Rufzeichen oder Kennzeichen suchen…',
  '● Live': '● Live', 'history': 'Verlauf', 'min': 'min', 'max': 'max', ' min': ' Min.', ' h ': ' Std. ',
  'on ground': 'am Boden', 'landed': 'gelandet', 'Close': 'Schließen', 'Open photo': 'Foto öffnen', 'Previous photo': 'Vorheriges Foto', 'Next photo': 'Nächstes Foto', 'Photo': 'Foto',
  '{0} entered the alert zone': '{0} hat die Alarmzone betreten', 'loading…': 'lädt…', 'error': 'Fehler', 'last updated': 'zuletzt aktualisiert',
  'wide view: center only, zoom in': 'Weitwinkel: nur Mitte, bitte hineinzoomen', 'demo (30x speed)': 'Demo (30-fache Geschwindigkeit)', 'FLIGHTS': 'FLÜGE',
  'loading route info · {0} / {1} aircraft': 'Routen werden geladen · {0} / {1} Flugzeuge', 'Click the map to set the zone center': 'Klicke auf die Karte, um den Zonenmittelpunkt zu setzen',
  'Alert zone set ({0} km)': 'Alarmzone gesetzt ({0} km)', '{0} km flown · {1} km to go': '{0} km geflogen · noch {1} km',
  'Registration': 'Kennzeichen', 'Speed': 'Geschwindigkeit', 'Heading': 'Kurs', 'Vertical speed': 'Vertikalgeschwindigkeit', 'Nearest airport': 'Nächster Flughafen', 'Position': 'Position', 'Owner': 'Halter',
  '★ Favorited': '★ Favorit', '☆ Favorite': '☆ Favorit', 'Loading route info…': 'Route wird geladen…', 'Route info not found': 'Route nicht gefunden',
  "Couldn't load route info": 'Route konnte nicht geladen werden', 'ICAO24': 'ICAO24', 'Squawk': 'Squawk', 'Category': 'Kategorie', 'Country': 'Land',
  "Couldn't load airport info": 'Flughafendaten konnten nicht geladen werden', 'Loading…': 'Lädt…', 'Open on Wikipedia': 'Auf Wikipedia öffnen', 'Feels like': 'Gefühlt', 'Gusts': 'Böen',
  'Humidity': 'Feuchte', 'Pressure': 'Luftdruck', 'Visibility': 'Sicht', 'Arrivals': 'Ankünfte', 'Departures': 'Abflüge', 'Weather unavailable': 'Wetter nicht verfügbar',
  'Loading weather…': 'Wetter wird geladen…', 'No aircraft loaded yet': 'Noch keine Flugzeuge geladen', 'No arrivals found nearby': 'Keine Ankünfte in der Nähe', 'No departures found nearby': 'Keine Abflüge in der Nähe',
  'Clear sky': 'Klar', 'Mostly clear': 'Überwiegend klar', 'Partly cloudy': 'Teils bewölkt', 'Overcast': 'Bedeckt', 'Fog': 'Nebel', 'Freezing fog': 'Gefrierender Nebel', 'Light drizzle': 'Leichter Nieselregen',
  'Drizzle': 'Nieselregen', 'Heavy drizzle': 'Starker Nieselregen', 'Freezing drizzle': 'Gefrierender Nieselregen', 'Light rain': 'Leichter Regen', 'Rain': 'Regen', 'Heavy rain': 'Starker Regen',
  'Freezing rain': 'Gefrierender Regen', 'Light snow': 'Leichter Schneefall', 'Snow': 'Schnee', 'Heavy snow': 'Starker Schneefall', 'Snow grains': 'Schneegriesel', 'Rain showers': 'Regenschauer', 'Violent showers': 'Heftige Schauer',
  'Snow showers': 'Schneeschauer', 'Thunderstorm': 'Gewitter', 'Thunderstorm, hail': 'Gewitter mit Hagel',
  'Hijacking': 'Entführung', 'Radio failure': 'Funkausfall', 'General emergency': 'Allgemeiner Notfall', 'Emergency': 'Notfall', 'What does this code mean?': 'Was bedeutet dieser Code?',
  '{0} landed': '{0} ist gelandet', '{0} took off': '{0} ist gestartet', 'Watching {0}: you will be notified when it takes off or lands': '{0} wird beobachtet: Du erhältst eine Meldung bei Start und Landung',
  'Watchlist': 'Beobachtungsliste', 'last seen {0} min ago': 'zuletzt vor {0} Min. gesehen', 'not seen yet': 'noch nicht gesehen', 'Remove': 'Entfernen', 'Not on the map right now': 'Gerade nicht auf der Karte',
  '🔔 Watching': '🔔 Beobachtet', '🔔 Watch': '🔔 Beobachten', "Today's flights": 'Heutige Flüge', "Couldn't load today's flights": 'Heutige Flüge konnten nicht geladen werden',
  'No flights recorded today': 'Heute keine Flüge aufgezeichnet', 'in flight': 'in der Luft', 'now': 'jetzt', 'Radar unavailable': 'Radar nicht verfügbar',
  'Already logged': 'Bereits eingetragen', 'new aircraft': 'neues Flugzeug', 'new type': 'neuer Typ', 'Logged {0}': '{0} eingetragen', 'Logbook': 'Logbuch', 'aircraft': 'Flugzeuge', 'types': 'Typen',
  'airlines': 'Airlines', 'Open logbook': 'Logbuch öffnen', 'Export CSV': 'CSV exportieren', 'The logbook is empty': 'Das Logbuch ist leer', 'Search the logbook…': 'Im Logbuch suchen…',
  'Nothing matches': 'Keine Treffer', 'The logbook is empty. Open a flight and press “Log sighting”.': 'Das Logbuch ist leer. Öffne einen Flug und tippe auf „Sichtung eintragen“.',
  'NEW AIRCRAFT': 'NEUES FLUGZEUG', 'NEW TYPE': 'NEUER TYP', '✓ Logged': '✓ Eingetragen', '📓 Log sighting': '📓 Sichtung eintragen',
  'Vert. speed': 'Steigrate', 'SkyTrack keeps running in the tray when you close the window': 'SkyTrack läuft im Hintergrund im Infobereich weiter, wenn du das Fenster schließt', '📓 Flight diary': '📓 Flugtagebuch',
  'Keep running in the tray': 'Im Infobereich weiterlaufen', 'Desktop notifications': 'Desktop-Benachrichtigungen', 'Flight diary': 'Flugtagebuch', 'Flights': 'Flüge', 'Distance': 'Strecke', 'Around the Earth': 'Erdumrundungen',
  '(est.)': '(geschätzt)', 'From': 'Von', 'To': 'Nach', 'Flight no.': 'Flugnr.', 'Add': 'Hinzufügen',
  'Your diary is empty. Add a flight above, or open a flight on the map and press “Add to diary”.': 'Dein Tagebuch ist leer. Füge oben einen Flug hinzu oder öffne einen Flug auf der Karte und tippe auf „Zum Tagebuch“.',
  'Unknown airport: use an IATA or ICAO code, e.g. IST or LTFM': 'Unbekannter Flughafen: IATA- oder ICAO-Code verwenden, z. B. FRA oder EDDF', 'Share image': 'Bild teilen', 'Add to diary': 'Zum Tagebuch', 'Added to your diary': 'Zum Tagebuch hinzugefügt',
  'Free flight tracker · no account, no ads': 'Kostenloser Flugtracker · ohne Konto, ohne Werbung', 'Image saved and copied to the clipboard': 'Bild gespeichert und in die Zwischenablage kopiert', 'Image saved': 'Bild gespeichert', 'Altitude & speed': 'Höhe & Geschwindigkeit',
  'Landing': 'Im Landeanflug', 'Approaching': 'Nähert sich', 'Departed': 'Gestartet', 'En route': 'Unterwegs',
  'A free flight tracker: no account, no ads. Here is a quick tour of what you can do.': 'Ein kostenloser Flugtracker: ohne Konto, ohne Werbung. Hier ein kurzer Rundgang durch das, was möglich ist.',
  'Aircraft within {0} of your spot': 'Flugzeuge im Umkreis von {0} um deinen Standort',
  'Airline code': 'Airline-Code',
  'Airport code': 'Flughafencode',
  'Alert zone set ({0})': 'Alarmzone gesetzt ({0})',
  'Alerts': 'Warnungen',
  'App': 'App',
  'Back': 'Zurück',
  'Callsign contains': 'Rufzeichen enthält',
  'Choose where you are': 'Wähle deinen Standort',
  'Click a plane to see its route, photo, altitude, speed and more. Click an airport (yellow dot) for its weather and arrivals.': 'Klicke auf ein Flugzeug für Route, Foto, Höhe, Geschwindigkeit und mehr. Klicke auf einen Flughafen (gelber Punkt) für Wetter und Ankünfte.',
  'Click any aircraft': 'Klicke auf ein Flugzeug',
  'Click the map to set your spot': 'Klicke auf die Karte, um deinen Standort zu setzen',
  'Click the map where you are, or type an airport code. SkyTrack lists the aircraft flying around that spot, with the direction to look and how high in the sky.': 'Klicke auf deinen Standort in der Karte oder gib einen Flughafencode ein. SkyTrack listet die Flugzeuge in der Umgebung auf, mit Blickrichtung und Höhe am Himmel.',
  'Click the map': 'Auf die Karte klicken',
  'Move my spot': 'Standort ändern',
  'Done': 'Fertig',
  'Next': 'Weiter',
  'Download': 'Herunterladen',
  'Downloading update {0}…': 'Update {0} wird geladen…',
  'Get a notification when an aircraft you care about shows up on the map.': 'Erhalte eine Benachrichtigung, wenn ein Flugzeug, das dich interessiert, auf der Karte erscheint.',
  'Headwind {0}': 'Gegenwind {0}',
  'Tailwind {0}': 'Rückenwind {0}',
  'Helicopters': 'Hubschrauber',
  'Hide or show the menu any time. Enjoy the sky!': 'Blende das Menü jederzeit aus oder ein. Viel Spaß am Himmel!',
  'High turbulence risk ahead (~{0})': 'Hohes Turbulenzrisiko voraus (~{0})',
  'Moderate turbulence possible ahead (~{0})': 'Mäßige Turbulenzen voraus möglich (~{0})',
  'Keep a flight diary, set alerts for rare aircraft, see what is flying overhead, and change units in Settings.': 'Führe ein Flugtagebuch, richte Warnungen für seltene Flugzeuge ein, sieh, was über dir fliegt, und ändere Einheiten in den Einstellungen.',
  'Menu button': 'Menü-Schaltfläche',
  'Military aircraft': 'Militärflugzeuge',
  'Narrow the map by altitude, speed, airport, airline or aircraft type.': 'Grenze die Karte nach Höhe, Geschwindigkeit, Flughafen, Airline oder Flugzeugtyp ein.',
  'New version {0} available': 'Neue Version {0} verfügbar',
  'No alerts yet. Add one above.': 'Noch keine Warnungen. Füge oben eine hinzu.',
  'Nothing overhead right now.': 'Gerade nichts über dir.',
  'Overhead': 'Über mir',
  'Radius': 'Radius',
  'Restart': 'Neu starten',
  'Search the whole world': 'Durchsuche die ganze Welt',
  'Settings': 'Einstellungen',
  'Show the tour again': 'Rundgang erneut zeigen',
  'Skip': 'Überspringen',
  'Switch the whole app between English, Turkish, Spanish, German and French.': 'Wechsle die ganze App zwischen Englisch, Türkisch, Spanisch, Deutsch und Französisch.',
  'Temperature': 'Temperatur',
  'Time': 'Uhrzeit',
  'Type a callsign, registration, aircraft type or airport. Results are not limited to the part of the map you see.': 'Gib ein Rufzeichen, Kennzeichen, einen Flugzeugtyp oder Flughafen ein. Die Ergebnisse sind nicht auf den sichtbaren Kartenausschnitt beschränkt.',
  'Units': 'Einheiten',
  'Update {0} is ready': 'Update {0} ist bereit',
  'Welcome to SkyTrack': 'Willkommen bei SkyTrack',
  'Worldwide': 'Weltweit',
  'Your language': 'Deine Sprache',
  'Your tools': 'Deine Werkzeuge',
  'e.g. A388, THY, TC-JNA': 'z. B. A388, DLH, D-AIMA',
  '{0} flown · {1} to go': '{0} geflogen · noch {1}',
  '{0} more aircraft match your alerts': '{0} weitere Flugzeuge passen zu deinen Warnungen',
  '⚙ Settings': '⚙ Einstellungen',
  '📍 Overhead': '📍 Über mir',
  '🔔 Alerts': '🔔 Warnungen',
  'A free OpenSky API client gives the wide view a much higher daily limit. Create one in your OpenSky account. It is stored encrypted on this computer.': 'Ein kostenloser OpenSky-API-Client gibt der Weitwinkelansicht ein viel höheres Tageslimit. Erstelle einen in deinem OpenSky-Konto. Er wird verschlüsselt auf diesem Computer gespeichert.',
  'Aircraft trails': 'Flugzeugspuren',
  'Based on the aircraft SkyTrack has loaded around the map.': 'Basierend auf den Flugzeugen, die SkyTrack rund um die Karte geladen hat.',
  'Busiest airports': 'Meistfrequentierte Flughäfen',
  'Clouds': 'Wolken',
  'Connected as {0}': 'Verbunden als {0}',
  'Could not store the credentials': 'Zugangsdaten konnten nicht gespeichert werden',
  'Data sources are busy, retrying shortly. Showing the last known positions.': 'Die Datenquellen sind ausgelastet, neuer Versuch in Kürze. Zuletzt bekannte Positionen werden angezeigt.',
  'Fastest': 'Schnellstes',
  'Highest': 'Höchstes',
  'How far back you can rewind': 'Wie weit du zurückspulen kannst',
  'In the air': 'In der Luft',
  'No connection to the data sources. Showing the last known positions.': 'Keine Verbindung zu den Datenquellen. Zuletzt bekannte Positionen werden angezeigt.',
  'On the ground': 'Am Boden',
  'OpenSky account (optional)': 'OpenSky-Konto (optional)',
  'Replay history': 'Wiedergabe-Verlauf',
  'Satellite imagery with clouds (NASA, latest daily image)': 'Satellitenbild mit Wolken (NASA, neuestes Tagesbild)',
  'Save': 'Speichern',
  'Stats': 'Statistiken',
  'Top aircraft types': 'Häufigste Flugzeugtypen',
  'Top airlines': 'Häufigste Airlines',
  'Trails': 'Spuren',
  'You can also try Demo mode.': 'Du kannst auch den Demo-Modus ausprobieren.',
  '{0} aircraft with an emergency code': '{0} Flugzeuge mit Notfallcode',
  '📊 Stats': '📊 Statistiken',
  'OpenSky account saved': 'OpenSky-Konto gespeichert',
  'OpenSky account removed': 'OpenSky-Konto entfernt',
  'Check for updates': 'Nach Updates suchen',
  'Checking…': 'Wird geprüft…',
  'You are up to date.': 'Du bist auf dem neuesten Stand.',
  'Version {0} found, downloading…': 'Version {0} gefunden, wird geladen…',
  'Could not check for updates: {0}': 'Updates konnten nicht geprüft werden: {0}',
  'Version {0} is available: use the bar at the bottom of the menu.': 'Version {0} ist verfügbar: nutze die Leiste unten im Menü.'
};
DICT.fr = {
  'Close menu': 'Fermer le menu', 'Open menu': 'Ouvrir le menu', 'Mode': 'Mode', 'Normal': 'Normal', 'Plane spotter': 'Spotter', 'Data': 'Données', 'Demo': 'Démo', 'Live': 'En direct',
  'Map': 'Carte', 'Airports': 'Aéroports', 'Alert zone': "Zone d'alerte", 'Radar': 'Radar', 'Rain radar': 'Radar de pluie', 'Zone radius': 'Rayon de la zone',
  'High turbulence risk ahead (~{0} km)': 'Risque élevé de turbulences devant (~{0} km)', 'Moderate turbulence possible ahead (~{0} km)': 'Turbulences modérées possibles devant (~{0} km)',
  'No turbulence reported or forecast on the route ahead': 'Aucune turbulence signalée ou prévue sur la route', 'Turbulence info unavailable': 'Infos turbulences indisponibles', 'Checking route ahead…': 'Vérification de la route…',
  'Wind': 'Vent', 'Headwind {0} kt': 'Vent de face {0} kt', 'Tailwind {0} kt': 'Vent arrière {0} kt', 'No significant head/tailwind': 'Pas de vent de face/arrière notable', '~{0}% of tank left (est., incl. reserve)': '~{0} % du réservoir restant (est., réserve incluse)', 'Fuel to go (est.)': 'Carburant restant (est.)', 'arrives {0}': 'arrivée {0}',
  'Turbulence': 'Turbulences', 'Turbulence advisories (SIGMET / G-AIRMET)': 'Avis de turbulences (SIGMET / G-AIRMET)', 'Wind arrows': 'Flèches de vent', 'Wind: FL050': 'Vent : FL050', 'Wind: FL100': 'Vent : FL100', 'Wind: FL180': 'Vent : FL180', 'Wind: FL300': 'Vent : FL300', 'Wind: FL340': 'Vent : FL340', 'Wind: FL390': 'Vent : FL390', 'Night': 'Nuit', 'Day / night': 'Jour / nuit',
  'Wind at {0}': 'Vent à {0}', 'Wind data unavailable': 'Données de vent indisponibles', 'Turbulence data unavailable': 'Données de turbulences indisponibles', 'Moderate turbulence': 'Turbulences modérées', 'Severe turbulence': 'Fortes turbulences', 'No turbulence advisories right now': 'Aucun avis de turbulences pour le moment',
  'Aircraft': 'Avions', '{0} s ago': 'il y a {0} s', '{0} min ago': 'il y a {0} min',
  'Standard': 'Standard', 'Light': 'Clair', 'Dark': 'Sombre', 'Filters': 'Filtres', 'Altitude': 'Altitude', 'Min speed': 'Vitesse min.', 'Airport': 'Aéroport',
  'Departure': 'Départ', 'Arrival': 'Arrivée', 'Departure ↔ arrival': 'Départ ↔ arrivée', 'Airline': 'Compagnie', 'e.g. THY, Pegasus, Lufthansa': 'p. ex. Air France, Transavia, Lufthansa',
  'Aircraft type': "Type d'appareil", 'e.g. B738, A320, boeing 777': 'p. ex. B738, A320, boeing 777', 'Show aircraft on the ground': 'Afficher les avions au sol',
  'Favorites only ★': 'Favoris uniquement ★', 'Search callsign or registration…': "Rechercher un indicatif ou une immatriculation…",
  '● Live': '● Direct', 'history': 'historique', 'min': 'min', 'max': 'max', ' min': ' min', ' h ': ' h ',
  'on ground': 'au sol', 'landed': 'atterri', 'Close': 'Fermer', 'Open photo': 'Ouvrir la photo', 'Previous photo': 'Photo précédente', 'Next photo': 'Photo suivante', 'Photo': 'Photo',
  '{0} entered the alert zone': '{0} est entré dans la zone d\'alerte', 'loading…': 'chargement…', 'error': 'erreur', 'last updated': 'dernière mise à jour',
  'wide view: center only, zoom in': 'vue large : centre seulement, zoomez', 'demo (30x speed)': 'démo (vitesse ×30)', 'FLIGHTS': 'VOLS',
  'loading route info · {0} / {1} aircraft': 'chargement des routes · {0} / {1} avions', 'Click the map to set the zone center': 'Cliquez sur la carte pour placer le centre de la zone',
  'Alert zone set ({0} km)': "Zone d'alerte définie ({0} km)", '{0} km flown · {1} km to go': '{0} km parcourus · {1} km restants',
  'Registration': 'Immatriculation', 'Speed': 'Vitesse', 'Heading': 'Cap', 'Vertical speed': 'Vitesse verticale', 'Nearest airport': 'Aéroport le plus proche', 'Position': 'Position', 'Owner': 'Propriétaire',
  '★ Favorited': '★ Favori', '☆ Favorite': '☆ Favori', 'Loading route info…': 'Chargement de la route…', 'Route info not found': 'Route introuvable',
  "Couldn't load route info": 'Impossible de charger la route', 'ICAO24': 'ICAO24', 'Squawk': 'Squawk', 'Category': 'Catégorie', 'Country': 'Pays',
  "Couldn't load airport info": "Impossible de charger les infos de l'aéroport", 'Loading…': 'Chargement…', 'Open on Wikipedia': 'Ouvrir sur Wikipédia', 'Feels like': 'Ressenti', 'Gusts': 'Rafales',
  'Humidity': 'Humidité', 'Pressure': 'Pression', 'Visibility': 'Visibilité', 'Arrivals': 'Arrivées', 'Departures': 'Départs', 'Weather unavailable': 'Météo indisponible',
  'Loading weather…': 'Chargement de la météo…', 'No aircraft loaded yet': "Aucun avion chargé pour l'instant", 'No arrivals found nearby': 'Aucune arrivée à proximité', 'No departures found nearby': 'Aucun départ à proximité',
  'Clear sky': 'Ciel dégagé', 'Mostly clear': 'Plutôt dégagé', 'Partly cloudy': 'Partiellement nuageux', 'Overcast': 'Couvert', 'Fog': 'Brouillard', 'Freezing fog': 'Brouillard givrant', 'Light drizzle': 'Bruine légère',
  'Drizzle': 'Bruine', 'Heavy drizzle': 'Bruine forte', 'Freezing drizzle': 'Bruine verglaçante', 'Light rain': 'Pluie légère', 'Rain': 'Pluie', 'Heavy rain': 'Forte pluie',
  'Freezing rain': 'Pluie verglaçante', 'Light snow': 'Neige légère', 'Snow': 'Neige', 'Heavy snow': 'Forte neige', 'Snow grains': 'Grains de neige', 'Rain showers': 'Averses', 'Violent showers': 'Fortes averses',
  'Snow showers': 'Averses de neige', 'Thunderstorm': 'Orage', 'Thunderstorm, hail': 'Orage avec grêle',
  'Hijacking': 'Détournement', 'Radio failure': 'Panne radio', 'General emergency': 'Urgence générale', 'Emergency': 'Urgence', 'What does this code mean?': 'Que signifie ce code ?',
  '{0} landed': '{0} a atterri', '{0} took off': '{0} a décollé', 'Watching {0}: you will be notified when it takes off or lands': '{0} suivi : vous serez prévenu au décollage et à l\'atterrissage',
  'Watchlist': 'Liste de suivi', 'last seen {0} min ago': 'vu il y a {0} min', 'not seen yet': 'pas encore vu', 'Remove': 'Retirer', 'Not on the map right now': 'Pas sur la carte pour le moment',
  '🔔 Watching': '🔔 Suivi', '🔔 Watch': '🔔 Suivre', "Today's flights": "Vols d'aujourd'hui", "Couldn't load today's flights": "Impossible de charger les vols d'aujourd'hui",
  'No flights recorded today': "Aucun vol enregistré aujourd'hui", 'in flight': 'en vol', 'now': 'maintenant', 'Radar unavailable': 'Radar indisponible',
  'Already logged': 'Déjà enregistré', 'new aircraft': 'nouvel avion', 'new type': 'nouveau type', 'Logged {0}': '{0} enregistré', 'Logbook': 'Carnet', 'aircraft': 'avions', 'types': 'types',
  'airlines': 'compagnies', 'Open logbook': 'Ouvrir le carnet', 'Export CSV': 'Exporter en CSV', 'The logbook is empty': 'Le carnet est vide', 'Search the logbook…': 'Rechercher dans le carnet…',
  'Nothing matches': 'Aucun résultat', 'The logbook is empty. Open a flight and press “Log sighting”.': 'Le carnet est vide. Ouvrez un vol et appuyez sur « Noter l\'observation ».',
  'NEW AIRCRAFT': 'NOUVEL AVION', 'NEW TYPE': 'NOUVEAU TYPE', '✓ Logged': '✓ Enregistré', '📓 Log sighting': "📓 Noter l'observation",
  'Vert. speed': 'Vit. verticale', 'SkyTrack keeps running in the tray when you close the window': "SkyTrack continue de tourner dans la zone de notification à la fermeture de la fenêtre", '📓 Flight diary': '📓 Carnet de vols',
  'Keep running in the tray': 'Rester actif dans la zone de notification', 'Desktop notifications': 'Notifications de bureau', 'Flight diary': 'Carnet de vols', 'Flights': 'Vols', 'Distance': 'Distance', 'Around the Earth': 'Tours du monde',
  '(est.)': '(est.)', 'From': 'De', 'To': 'Vers', 'Flight no.': 'N° de vol', 'Add': 'Ajouter',
  'Your diary is empty. Add a flight above, or open a flight on the map and press “Add to diary”.': 'Votre carnet est vide. Ajoutez un vol ci-dessus ou ouvrez-en un sur la carte et appuyez sur « Ajouter au carnet ».',
  'Unknown airport: use an IATA or ICAO code, e.g. IST or LTFM': 'Aéroport inconnu : utilisez un code IATA ou OACI, p. ex. CDG ou LFPG', 'Share image': "Partager l'image", 'Add to diary': 'Ajouter au carnet', 'Added to your diary': 'Ajouté à votre carnet',
  'Free flight tracker · no account, no ads': 'Suivi de vols gratuit · sans compte, sans pub', 'Image saved and copied to the clipboard': 'Image enregistrée et copiée dans le presse-papiers', 'Image saved': 'Image enregistrée', 'Altitude & speed': 'Altitude et vitesse',
  'Landing': "En approche finale", 'Approaching': "En approche", 'Departed': 'Parti', 'En route': 'En route',
  'A free flight tracker: no account, no ads. Here is a quick tour of what you can do.': 'Un suivi de vols gratuit : sans compte, sans pub. Un tour rapide de ce que vous pouvez faire.',
  'Aircraft within {0} of your spot': 'Avions à moins de {0} de votre position',
  'Airline code': 'Code de compagnie',
  'Airport code': 'Code d\'aéroport',
  'Alert zone set ({0})': 'Zone d\'alerte définie ({0})',
  'Alerts': 'Alertes',
  'App': 'Application',
  'Back': 'Retour',
  'Callsign contains': 'L\'indicatif contient',
  'Choose where you are': 'Choisissez où vous êtes',
  'Click a plane to see its route, photo, altitude, speed and more. Click an airport (yellow dot) for its weather and arrivals.': 'Cliquez sur un avion pour voir sa route, sa photo, son altitude, sa vitesse et plus. Cliquez sur un aéroport (point jaune) pour la météo et les arrivées.',
  'Click any aircraft': 'Cliquez sur un avion',
  'Click the map to set your spot': 'Cliquez sur la carte pour placer votre position',
  'Click the map where you are, or type an airport code. SkyTrack lists the aircraft flying around that spot, with the direction to look and how high in the sky.': 'Cliquez sur la carte là où vous êtes, ou saisissez un code d\'aéroport. SkyTrack liste les avions qui volent autour, avec la direction où regarder et la hauteur dans le ciel.',
  'Click the map': 'Cliquer sur la carte',
  'Move my spot': 'Déplacer ma position',
  'Done': 'Terminé',
  'Next': 'Suivant',
  'Download': 'Télécharger',
  'Downloading update {0}…': 'Téléchargement de la mise à jour {0}…',
  'Get a notification when an aircraft you care about shows up on the map.': 'Recevez une notification quand un avion qui vous intéresse apparaît sur la carte.',
  'Headwind {0}': 'Vent de face {0}',
  'Tailwind {0}': 'Vent arrière {0}',
  'Helicopters': 'Hélicoptères',
  'Hide or show the menu any time. Enjoy the sky!': 'Masquez ou affichez le menu à tout moment. Profitez du ciel !',
  'High turbulence risk ahead (~{0})': 'Risque élevé de turbulences devant (~{0})',
  'Moderate turbulence possible ahead (~{0})': 'Turbulences modérées possibles devant (~{0})',
  'Keep a flight diary, set alerts for rare aircraft, see what is flying overhead, and change units in Settings.': 'Tenez un carnet de vols, créez des alertes pour les avions rares, voyez ce qui vole au-dessus de vous et changez les unités dans les Réglages.',
  'Menu button': 'Bouton du menu',
  'Military aircraft': 'Avions militaires',
  'Narrow the map by altitude, speed, airport, airline or aircraft type.': 'Affinez la carte par altitude, vitesse, aéroport, compagnie ou type d\'appareil.',
  'New version {0} available': 'Nouvelle version {0} disponible',
  'No alerts yet. Add one above.': 'Aucune alerte pour l\'instant. Ajoutez-en une ci-dessus.',
  'Nothing overhead right now.': 'Rien au-dessus de vous pour le moment.',
  'Overhead': 'Au-dessus de moi',
  'Radius': 'Rayon',
  'Restart': 'Redémarrer',
  'Search the whole world': 'Cherchez dans le monde entier',
  'Settings': 'Réglages',
  'Show the tour again': 'Revoir la visite',
  'Skip': 'Passer',
  'Switch the whole app between English, Turkish, Spanish, German and French.': 'Changez toute l\'application entre anglais, turc, espagnol, allemand et français.',
  'Temperature': 'Température',
  'Time': 'Heure',
  'Type a callsign, registration, aircraft type or airport. Results are not limited to the part of the map you see.': 'Saisissez un indicatif, une immatriculation, un type d\'appareil ou un aéroport. Les résultats ne se limitent pas à la partie visible de la carte.',
  'Units': 'Unités',
  'Update {0} is ready': 'La mise à jour {0} est prête',
  'Welcome to SkyTrack': 'Bienvenue sur SkyTrack',
  'Worldwide': 'Dans le monde',
  'Your language': 'Votre langue',
  'Your tools': 'Vos outils',
  'e.g. A388, THY, TC-JNA': 'p. ex. A388, AFR, F-HPJA',
  '{0} flown · {1} to go': '{0} parcourus · {1} restants',
  '{0} more aircraft match your alerts': '{0} autres avions correspondent à vos alertes',
  '⚙ Settings': '⚙ Réglages',
  '📍 Overhead': '📍 Au-dessus de moi',
  '🔔 Alerts': '🔔 Alertes',
  'A free OpenSky API client gives the wide view a much higher daily limit. Create one in your OpenSky account. It is stored encrypted on this computer.': 'Un client d\'API OpenSky gratuit donne à la vue large une limite quotidienne bien plus élevée. Créez-en un dans votre compte OpenSky. Il est stocké chiffré sur cet ordinateur.',
  'Aircraft trails': 'Traînées des avions',
  'Based on the aircraft SkyTrack has loaded around the map.': 'D\'après les appareils que SkyTrack a chargés autour de la carte.',
  'Busiest airports': 'Aéroports les plus actifs',
  'Clouds': 'Nuages',
  'Connected as {0}': 'Connecté en tant que {0}',
  'Could not store the credentials': 'Impossible d\'enregistrer les identifiants',
  'Data sources are busy, retrying shortly. Showing the last known positions.': 'Les sources de données sont saturées, nouvel essai dans un instant. Dernières positions connues affichées.',
  'Fastest': 'Le plus rapide',
  'Highest': 'Le plus haut',
  'How far back you can rewind': 'Jusqu\'où vous pouvez revenir en arrière',
  'In the air': 'En vol',
  'No connection to the data sources. Showing the last known positions.': 'Pas de connexion aux sources de données. Dernières positions connues affichées.',
  'On the ground': 'Au sol',
  'OpenSky account (optional)': 'Compte OpenSky (facultatif)',
  'Replay history': 'Historique de relecture',
  'Satellite imagery with clouds (NASA, latest daily image)': 'Image satellite avec nuages (NASA, dernière image quotidienne)',
  'Save': 'Enregistrer',
  'Stats': 'Statistiques',
  'Top aircraft types': 'Types d\'appareils les plus fréquents',
  'Top airlines': 'Compagnies les plus fréquentes',
  'Trails': 'Traînées',
  'You can also try Demo mode.': 'Vous pouvez aussi essayer le mode démo.',
  '{0} aircraft with an emergency code': '{0} appareils avec un code d\'urgence',
  '📊 Stats': '📊 Statistiques',
  'OpenSky account saved': 'Compte OpenSky enregistré',
  'OpenSky account removed': 'Compte OpenSky supprimé',
  'Check for updates': 'Rechercher des mises à jour',
  'Checking…': 'Vérification…',
  'You are up to date.': 'Vous êtes à jour.',
  'Version {0} found, downloading…': 'Version {0} trouvée, téléchargement…',
  'Could not check for updates: {0}': 'Impossible de rechercher les mises à jour : {0}',
  'Version {0} is available: use the bar at the bottom of the menu.': 'La version {0} est disponible : utilisez la barre en bas du menu.'
};

// Trip tools (seat tips, route check, watch a flight, tracking link)
Object.assign(DICT.tr, {
  'Thin ADS-B coverage here: some aircraft may be missing': 'Burada ADS-B alıcı ağı seyrek: bazı uçaklar eksik olabilir',
  'Seat tip': 'Koltuk ipucu',
  'Sun side': 'Güneş tarafı',
  'Over the wings you feel turbulence least, the back rows most.': 'Kanat üstünde türbülansı en az, arka sıralarda en çok hissedersin.',
  'Right side': 'Sağ taraf',
  'Left side': 'Sol taraf',
  'Route check': 'Rota kontrolü',
  '🧭 Route check': '🧭 Rota kontrolü',
  'Is there turbulence on a route? Pick two airports to see what is reported along the way at three cruise altitudes.': 'Bir rotada türbülans var mı? İki havalimanı seç, yol boyunca üç seyir irtifasında neler bildirildiğini gör.',
  'From': 'Nereden',
  'To': 'Nereye',
  'Check route': 'Rotayı kontrol et',
  'Use selected flight': 'Seçili uçuşu kullan',
  'High turbulence risk': 'Yüksek türbülans riski',
  'Moderate turbulence possible': 'Orta türbülans mümkün',
  'Nothing reported': 'Bildirilen bir şey yok',
  'first about {0} from {1}': '{1} çıkışından yaklaşık {0} sonra',
  'Based on SIGMET / G-AIRMET advisories and pilot reports from the last 2 hours. Nothing reported is not a guarantee.': 'SIGMET / G-AIRMET uyarılarına ve son 2 saatteki pilot raporlarına dayanır. Bildirilen bir şey olmaması garanti değildir.',
  'Show on map': 'Haritada göster',
  '{0}: high turbulence risk ahead (~{1}). Keep your seat belt fastened.': '{0}: önünde yüksek türbülans riski var (~{1}). Emniyet kemerini bağlı tut.',
  '{0}: moderate turbulence possible ahead (~{1}). Keep your seat belt fastened.': '{0}: önünde orta türbülans ihtimali var (~{1}). Emniyet kemerini bağlı tut.',
  '{0}: nothing reported on the route ahead any more': '{0}: önündeki yolda artık bildirilen bir şey yok',
  'Enter a flight number, e.g. TK1 or THY1': 'Bir uçuş numarası yaz, ör. TK1 ya da THY1',
  'Watching {0}: SkyTrack tells you when it is in the air, and about turbulence ahead': '{0} takipte: havalandığında ve önünde türbülans olduğunda SkyTrack haber verir',
  '{0} is in the air: watching': '{0} havada: takipte',
  'Watch a flight': 'Bir uçuşu takip et',
  'Enter a flight number. You get a notification when it is in the air and when there is turbulence ahead.': 'Bir uçuş numarası yaz. Havalandığında ve önünde türbülans olduğunda bildirim alırsın.',
  'Flight number, e.g. TK1': 'Uçuş numarası, ör. TK1',
  'Watch': 'Takip et',
  'waiting for departure': 'kalkış bekleniyor',
  'Copy tracking link': 'Takip bağlantısını kopyala',
  'Tracking link copied': 'Takip bağlantısı kopyalandı'
});
Object.assign(DICT.es, {
  'Thin ADS-B coverage here: some aircraft may be missing': 'Cobertura ADS-B escasa aquí: pueden faltar aviones',
  'Seat tip': 'Consejo de asiento',
  'Sun side': 'Lado del sol',
  'Over the wings you feel turbulence least, the back rows most.': 'Sobre las alas se nota menos la turbulencia, en las filas traseras más.',
  'Right side': 'Lado derecho',
  'Left side': 'Lado izquierdo',
  'Route check': 'Revisión de ruta',
  '🧭 Route check': '🧭 Revisión de ruta',
  'Is there turbulence on a route? Pick two airports to see what is reported along the way at three cruise altitudes.': '¿Hay turbulencia en una ruta? Elige dos aeropuertos y mira qué se notifica por el camino a tres altitudes de crucero.',
  'From': 'Origen',
  'To': 'Destino',
  'Check route': 'Revisar ruta',
  'Use selected flight': 'Usar el vuelo seleccionado',
  'High turbulence risk': 'Alto riesgo de turbulencia',
  'Moderate turbulence possible': 'Posible turbulencia moderada',
  'Nothing reported': 'Nada notificado',
  'first about {0} from {1}': 'primero a unos {0} de {1}',
  'Based on SIGMET / G-AIRMET advisories and pilot reports from the last 2 hours. Nothing reported is not a guarantee.': 'Basado en avisos SIGMET / G-AIRMET e informes de pilotos de las últimas 2 horas. Que no haya nada notificado no es una garantía.',
  'Show on map': 'Ver en el mapa',
  '{0}: high turbulence risk ahead (~{1}). Keep your seat belt fastened.': '{0}: alto riesgo de turbulencia por delante (~{1}). Mantén el cinturón abrochado.',
  '{0}: moderate turbulence possible ahead (~{1}). Keep your seat belt fastened.': '{0}: posible turbulencia moderada por delante (~{1}). Mantén el cinturón abrochado.',
  '{0}: nothing reported on the route ahead any more': '{0}: ya no hay nada notificado en la ruta por delante',
  'Enter a flight number, e.g. TK1 or THY1': 'Escribe un número de vuelo, p. ej. TK1 o THY1',
  'Watching {0}: SkyTrack tells you when it is in the air, and about turbulence ahead': 'Siguiendo {0}: SkyTrack te avisa cuando esté en el aire y de la turbulencia por delante',
  '{0} is in the air: watching': '{0} está en el aire: siguiéndolo',
  'Watch a flight': 'Seguir un vuelo',
  'Enter a flight number. You get a notification when it is in the air and when there is turbulence ahead.': 'Escribe un número de vuelo. Recibes una notificación cuando esté en el aire y cuando haya turbulencia por delante.',
  'Flight number, e.g. TK1': 'Número de vuelo, p. ej. TK1',
  'Watch': 'Seguir',
  'waiting for departure': 'esperando la salida',
  'Copy tracking link': 'Copiar enlace de seguimiento',
  'Tracking link copied': 'Enlace de seguimiento copiado'
});
Object.assign(DICT.de, {
  'Thin ADS-B coverage here: some aircraft may be missing': 'Dünne ADS-B-Abdeckung hier: Flugzeuge können fehlen',
  'Seat tip': 'Sitzplatz-Tipp',
  'Sun side': 'Sonnenseite',
  'Over the wings you feel turbulence least, the back rows most.': 'Über den Tragflächen spürt man Turbulenzen am wenigsten, in den hinteren Reihen am meisten.',
  'Right side': 'Rechte Seite',
  'Left side': 'Linke Seite',
  'Route check': 'Routen-Check',
  '🧭 Route check': '🧭 Routen-Check',
  'Is there turbulence on a route? Pick two airports to see what is reported along the way at three cruise altitudes.': 'Gibt es Turbulenzen auf einer Strecke? Wähle zwei Flughäfen und sieh, was unterwegs auf drei Reiseflughöhen gemeldet ist.',
  'From': 'Von',
  'To': 'Nach',
  'Check route': 'Strecke prüfen',
  'Use selected flight': 'Gewählten Flug verwenden',
  'High turbulence risk': 'Hohes Turbulenzrisiko',
  'Moderate turbulence possible': 'Mäßige Turbulenzen möglich',
  'Nothing reported': 'Nichts gemeldet',
  'first about {0} from {1}': 'erstmals etwa {0} ab {1}',
  'Based on SIGMET / G-AIRMET advisories and pilot reports from the last 2 hours. Nothing reported is not a guarantee.': 'Basiert auf SIGMET- / G-AIRMET-Meldungen und Pilotenberichten der letzten 2 Stunden. „Nichts gemeldet“ ist keine Garantie.',
  'Show on map': 'Auf der Karte zeigen',
  '{0}: high turbulence risk ahead (~{1}). Keep your seat belt fastened.': '{0}: hohes Turbulenzrisiko voraus (~{1}). Bleib angeschnallt.',
  '{0}: moderate turbulence possible ahead (~{1}). Keep your seat belt fastened.': '{0}: mäßige Turbulenzen möglich voraus (~{1}). Bleib angeschnallt.',
  '{0}: nothing reported on the route ahead any more': '{0}: auf der Strecke voraus ist nichts mehr gemeldet',
  'Enter a flight number, e.g. TK1 or THY1': 'Gib eine Flugnummer ein, z. B. TK1 oder THY1',
  'Watching {0}: SkyTrack tells you when it is in the air, and about turbulence ahead': '{0} wird beobachtet: SkyTrack sagt dir, wann er in der Luft ist und ob Turbulenzen voraus liegen',
  '{0} is in the air: watching': '{0} ist in der Luft: wird beobachtet',
  'Watch a flight': 'Einen Flug beobachten',
  'Enter a flight number. You get a notification when it is in the air and when there is turbulence ahead.': 'Gib eine Flugnummer ein. Du wirst benachrichtigt, wenn er in der Luft ist und wenn Turbulenzen voraus liegen.',
  'Flight number, e.g. TK1': 'Flugnummer, z. B. TK1',
  'Watch': 'Beobachten',
  'waiting for departure': 'wartet auf den Abflug',
  'Copy tracking link': 'Tracking-Link kopieren',
  'Tracking link copied': 'Tracking-Link kopiert'
});
Object.assign(DICT.fr, {
  'Thin ADS-B coverage here: some aircraft may be missing': 'Couverture ADS-B faible ici : des avions peuvent manquer',
  'Seat tip': 'Conseil de siège',
  'Sun side': 'Côté du soleil',
  'Over the wings you feel turbulence least, the back rows most.': 'Au-dessus des ailes, on ressent le moins les turbulences, dans les rangées arrière le plus.',
  'Right side': 'Côté droit',
  'Left side': 'Côté gauche',
  'Route check': 'Vérification de route',
  '🧭 Route check': '🧭 Vérification de route',
  'Is there turbulence on a route? Pick two airports to see what is reported along the way at three cruise altitudes.': 'Y a-t-il des turbulences sur une route ? Choisissez deux aéroports pour voir ce qui est signalé en chemin à trois altitudes de croisière.',
  'From': 'Départ',
  'To': 'Arrivée',
  'Check route': 'Vérifier la route',
  'Use selected flight': 'Utiliser le vol sélectionné',
  'High turbulence risk': 'Fort risque de turbulences',
  'Moderate turbulence possible': 'Turbulences modérées possibles',
  'Nothing reported': 'Rien de signalé',
  'first about {0} from {1}': 'd\'abord à environ {0} de {1}',
  'Based on SIGMET / G-AIRMET advisories and pilot reports from the last 2 hours. Nothing reported is not a guarantee.': 'Basé sur les avis SIGMET / G-AIRMET et les rapports de pilotes des 2 dernières heures. Rien de signalé ne veut pas dire garanti.',
  'Show on map': 'Voir sur la carte',
  '{0}: high turbulence risk ahead (~{1}). Keep your seat belt fastened.': '{0} : fort risque de turbulences devant (~{1}). Gardez votre ceinture attachée.',
  '{0}: moderate turbulence possible ahead (~{1}). Keep your seat belt fastened.': '{0} : turbulences modérées possibles devant (~{1}). Gardez votre ceinture attachée.',
  '{0}: nothing reported on the route ahead any more': '{0} : plus rien de signalé sur la route devant',
  'Enter a flight number, e.g. TK1 or THY1': 'Saisissez un numéro de vol, p. ex. TK1 ou THY1',
  'Watching {0}: SkyTrack tells you when it is in the air, and about turbulence ahead': '{0} suivi : SkyTrack vous prévient quand il est en vol, et des turbulences devant',
  '{0} is in the air: watching': '{0} est en vol : suivi',
  'Watch a flight': 'Suivre un vol',
  'Enter a flight number. You get a notification when it is in the air and when there is turbulence ahead.': 'Saisissez un numéro de vol. Vous êtes notifié quand il est en vol et quand il y a des turbulences devant.',
  'Flight number, e.g. TK1': 'Numéro de vol, p. ex. TK1',
  'Watch': 'Suivre',
  'waiting for departure': 'en attente du départ',
  'Copy tracking link': 'Copier le lien de suivi',
  'Tracking link copied': 'Lien de suivi copié'
});

// Thinning out crowded areas when zoomed out
Object.assign(DICT.tr, { 'Showing {0} of {1} aircraft · zoom in for all': '{1} uçaktan {0} tanesi gösteriliyor · hepsi için yakınlaştır', 'Thin out crowded areas when zoomed out': 'Uzaklaşınca kalabalık bölgelerdeki uçakları seyrelt' });
Object.assign(DICT.es, { 'Showing {0} of {1} aircraft · zoom in for all': 'Mostrando {0} de {1} aviones · acércate para ver todos', 'Thin out crowded areas when zoomed out': 'Reducir aviones en zonas concurridas al alejar' });
Object.assign(DICT.de, { 'Showing {0} of {1} aircraft · zoom in for all': '{0} von {1} Flugzeugen werden angezeigt · zoome hinein für alle', 'Thin out crowded areas when zoomed out': 'Beim Herauszoomen volle Gebiete ausdünnen' });
Object.assign(DICT.fr, { 'Showing {0} of {1} aircraft · zoom in for all': '{0} avions sur {1} affichés · zoomez pour tous les voir', 'Thin out crowded areas when zoomed out': 'Réduire les avions dans les zones denses en dézoomant' });

// Wide view status while the fill is still going
Object.assign(DICT.tr, { 'Wide view: filling in, zoom in for all': 'Geniş görünüm: dolduruluyor, hepsi için yakınlaştır' });
Object.assign(DICT.es, { 'Wide view: filling in, zoom in for all': 'Vista amplia: rellenando, acércate para ver todos' });
Object.assign(DICT.de, { 'Wide view: filling in, zoom in for all': 'Weite Ansicht: wird aufgefüllt, zoome hinein für alle' });
Object.assign(DICT.fr, { 'Wide view: filling in, zoom in for all': 'Vue large : remplissage en cours, zoomez pour tous les voir' });

// Landed card text
Object.assign(DICT.tr, { 'landed {0} ago': '{0} önce indi', 'just landed': 'az önce indi' });
Object.assign(DICT.es, { 'landed {0} ago': 'aterrizó hace {0}', 'just landed': 'acaba de aterrizar' });
Object.assign(DICT.de, { 'landed {0} ago': 'vor {0} gelandet', 'just landed': 'gerade gelandet' });
Object.assign(DICT.fr, { 'landed {0} ago': 'a atterri il y a {0}', 'just landed': 'vient d\'atterrir' });
